import type { Walkthrough } from "./types";

/**
 * Scenario 9 (v1.2 hero) — "OnRamp", a Series B SaaS, uses Linear as their PM
 * tool. A backend engineer pulls Linear ticket PLAT-4471 and rides the
 * v1.2 PM-MCP pipeline end-to-end: app-architect reads the ticket and
 * drafts the sprint, git-ops opens the PR with the ticket linked,
 * deploy-ops creates a deploy ticket and transitions it through the
 * environments, monitoring-ops opens an incident ticket the next day
 * when an alert fires. Jira + GitHub Issues are called out in the
 * config artifact as drop-in alternatives.
 */
export const pmPipelineLinear: Walkthrough = {
  id: "pm-pipeline-linear",
  title: "Run a Linear ticket end-to-end through the v1.2 pipeline",
  tagline: "PM-aware pipeline, Linear-led",
  summary:
    "v1.2 hero scenario: app-architect reads PLAT-4471 from Linear, drafts a sprint, git-ops links the PR back to the ticket, deploy-ops auto-creates a deploy ticket, monitoring-ops opens an incident ticket the next morning when an alert fires.",
  description:
    "OnRamp is a Series B SaaS startup with ~30 engineers; their PM tool is Linear. A backend engineer named Sam picks up PLAT-4471 (\"Add CSV export to /api/customers\") and rides the v1.2 PM-MCP pipeline from ticket → ship → first incident. The v1.2 release wires the opchain skills into the PM-tool MCPs Anthropic ships with Claude Code: app-architect /discover and /roadmap consume tickets and write sprints back; git-ops shapes branch + commit + PR from the ticket; deploy-ops creates deploy tickets per environment; monitoring-ops opens incident tickets when alerts fire. Linear is the named tool here; the same flow runs against Jira (Atlassian MCP) or GitHub Issues with a one-line config change. The artifact set is a complete Linear timeline that traces a single piece of work from \"someone filed a ticket\" to \"prod is healthy after a tiny incident.\"",
  inputs: [
    "Series B SaaS · ~30 engineers · existing repo · Linear as system-of-record",
    "Linear ticket PLAT-4471 · \"Add CSV export to /api/customers\" · estimate: 2",
    "Standard opchain stack already wired (app-architect, git-ops, code-auditor, deploy-ops, monitoring-ops, all v1.2)",
    "Linear MCP server configured · `.opchain/pm.yaml` present at repo root",
  ],
  outputs: [
    {
      id: "pm-config",
      label: "`.opchain/pm.yaml` for Linear (with Jira / GitHub Issues alts)",
      kind: "config.yaml",
      body:
`# .opchain/pm.yaml — OnRamp's Linear configuration
# Generated by app-architect /init; reviewed quarterly.
# Schema reference: skills/integrations-engineer/references/pm-config-schema.md

provider: linear
team_or_project: PLAT
mcp_server: linear        # name of the configured MCP in claude-code's mcp.json

issue_types:
  feature:  Feature
  bug:      Bug
  chore:    Chore
  deploy:   Deploy        # used by deploy-ops
  incident: Incident      # used by monitoring-ops
  release:  Release       # used by release-ops (v1.3+)

states:
  in_progress: "In Progress"
  in_review:   "In Review"
  done:        "Done"
  extended:
    blocked:                       "Blocked"
    staging-verified:              "Staging verified"
    shipped:                       "Shipped"
    rolled-back:                   "Rolled back"
    resolved-pending-postmortem:   "Resolved (PM pending)"

labels_default: [opchain, agent-driven]

# Map domain → on-call user for auto-assigning remediation sub-tickets.
remediation_owners:
  backend:  sam@onramp.dev
  frontend: priya@onramp.dev
  data:     yusuf@onramp.dev
  infra:    vee@onramp.dev

# v1.2 behaviour toggles
create_child_tickets: true        # app-architect /roadmap creates one child per sprint
cycle_aware: true                 # match tickets to current Linear cycle for sprint capacity check
comment_dedupe_window: 7d         # how far back the marker lookup considers a comment "recent"
pr_template: ".github/pull_request_template.md"

# State transitions that require a passing audit gate before deploy-ops will fire.
audit_required_for_state_transitions:
  - "Staging verified"
  - "Shipped"

# Map service → PagerDuty escalation policy (used by monitoring-ops when filing incidents).
pagerduty_routing:
  api/customers:        EP-PLAT-BACKEND
  api/customers.csv:    EP-PLAT-BACKEND
  api/auth:             EP-PLAT-BACKEND
  worker/webhooks:      EP-PLAT-INFRA

# Branch + worktree naming. git-ops fills the {slug} from the ticket title.
worktree_naming: "feat/{ticket-id}-{slug}"   # e.g. feat/PLAT-4471-add-csv-export-customers

# ──────────────────────────────────────────────────────────
# Drop-in for Jira (Atlassian MCP):
#
#   provider: jira
#   team_or_project: PLAT          # the Jira project key
#   mcp_server: jira-cloud
#   issue_types:
#     feature:  Story
#     bug:      Bug
#     chore:    Task
#     deploy:   Task
#     incident: Incident
#     release:  Task
#   states:
#     in_progress: "In Progress"
#     in_review:   "In Review"
#     done:        "Done"
#     extended:
#       blocked:           "Blocked"
#       staging-verified:  "In Staging"
#       shipped:           "Shipped"
#       ...
#
# Drop-in for GitHub Issues:
#
#   provider: github-issues
#   team_or_project: onramp-inc/platform   # owner/repo
#   mcp_server: github
#   issue_types:                  # GH labels for issue-type discrimination
#     feature:  type:feature
#     bug:      type:bug
#     deploy:   type:deploy
#     incident: type:incident
#   states:                       # GH issue state model is binary; states map to labels
#     in_progress: "status:in-progress"
#     in_review:   "status:in-review"
#     done:        closed         # the literal "closed" state, not a label
# ──────────────────────────────────────────────────────────
`,
    },
    {
      id: "ticket-detail",
      label: "PLAT-4471 — the source ticket",
      kind: "linear.md",
      body:
`# PLAT-4471 — Add CSV export to /api/customers

**URL:** https://linear.app/onramp/issue/PLAT-4471
**Project:** Platform · **Cycle:** 2026-W19 · **Type:** Feature · **State:** Todo · **Priority:** Medium (P3) · **Estimate:** 2 · **Reporter:** ana@onramp.dev · **Assignee:** sam@onramp.dev · **Labels:** customer-success, exports, opchain, agent-driven
**Watchers:** ana@onramp.dev, lily@onramp.dev (CS Lead) · **Sub-issues:** 0 · **Linked PRs:** 0 (will fill on /git-sync)
**Created:** 2026-05-01T16:42:11Z · **Updated:** 2026-05-04T09:08:04Z · **Due:** 2026-05-08 (CS team requested before EoW)

## Description

Customer Success has been asking for a "Download as CSV" affordance on the
customer-list view for ~6 weeks. Right now they screenshot the table view
in the admin app and paste into Google Sheets. That worked when the median
account had ~20 customers; it doesn't scale past ~50 rows, and our 5 biggest
tenants are well past 100k customers each. **Lily flagged this as a top-3
CS productivity blocker in the Q2 planning doc.**

We already expose \`GET /api/customers\` (returns paginated JSON with the
same filter set CS uses in the admin UI: status, plan, free-text search).
The cleanest path is a sibling \`/api/customers.csv\` endpoint that returns
the same data as RFC 4180-compliant CSV, respecting the same query
parameters. CS would call it from the existing "Download" button on the
customer-list (PLAT-4472 owns the button itself).

## Technical context

- Handler lives in \`src/api/customers.ts\`; service-role function is
  \`getCustomersForTenant({ filters, cursor, limit })\` in
  \`src/services/customers.ts\`.
- The service already supports cursor pagination. **It does NOT currently
  expose a streaming mode** — the JSON endpoint buffers and serialises in
  one shot. We need to add streaming for the CSV path (see acceptance
  criteria) without regressing the JSON path.
- Tenant isolation is enforced by the existing \`requireTenant\`
  middleware; the CSV endpoint should sit behind the same middleware.

## Business context

- Filed by ana@ on behalf of the CS team. The specific incident that
  pushed this from "nice to have" to "this cycle": **acme-inc**
  (108k customers) needed a full account export for their compliance
  team last Thursday; CS spent ~4 hours hand-stitching screenshots.
- One Excel-on-Windows user (Karen at \`midmarket-corp\`) can't open
  CSVs without a BOM — past CSV experiments in the admin app failed
  on her machine. **BOM is required, not optional.**

## Acceptance criteria

- [ ] \`GET /api/customers.csv\` returns \`text/csv; charset=utf-8\`.
- [ ] \`Content-Disposition: attachment; filename="customers-{tenant-slug}-{yyyy-mm-dd}.csv"\`.
- [ ] Same query params as \`/api/customers\` (\`?status=&plan=&q=\`) work and are
      validated identically (reuse the existing Zod schema).
- [ ] BOM prefix (\`\\uFEFF\`) for Excel-on-Windows compatibility.
- [ ] Streams response row-by-row (no full buffering in memory — the
      \`acme-inc\` tenant has 108k customers; a buffered response would
      OOM the worker at the current 128MB limit).
- [ ] Auth + tenant isolation matches \`/api/customers\` exactly (cross-tenant
      request returns 403; unauthenticated returns 401).
- [ ] RFC 4180 escaping for commas, quotes, CR/LF in values.
- [ ] Header row matches the admin UI's column order: id, name, email,
      plan, status, mrr_cents, created_at, last_active_at.

## Definition of done

- [ ] All acceptance criteria checked.
- [ ] Unit tests + integration test against \`big-tenant\` seeded fixture.
- [ ] code-auditor /audit pre-deploy returns Grade A or better.
- [ ] bug-check pre-commit PASS.
- [ ] Manual smoke against staging with a real CS user (lily@) confirming
      the file opens cleanly in Sheets AND in Excel-on-Windows.
- [ ] Deployed to prod via the standard deploy-ops gate.

## Investigation notes (ana — 2026-05-04)

I poked at the existing JSON endpoint to understand the shape. A few
findings:

- \`getCustomersForTenant\` already takes a \`limit\` param; calling it
  without one returns the configured default (200 rows). To stream we'd
  need a generator/cursor-based variant.
- The audit-log endpoint (PLAT-4011, shipped 6 months ago) already
  streams CSV via a similar pattern. **Sam: look at \`src/api/audit-log.csv.ts\`
  for the streaming template.** It uses a \`ReadableStream\` wrapping a
  cursor-driven generator and pipes through a CSV escaper helper.
- Heap profiling on staging with \`big-tenant\` (108k rows): the existing
  JSON endpoint peaks at ~620MB heap when called without a limit. We
  cannot ship CSV using that pattern.

## Out of scope

- The "Download as CSV" UI button — owned by PLAT-4472 (Priya). Separately
  estimated.
- Excel native \`.xlsx\` export — premium-tier feature, separate decision
  (PLAT-3201, parked).
- Per-column filtering UI — also CS-requested but separate (PLAT-3987).
- Background-job CSV (for tenants > 500k customers) — not needed yet; the
  streaming approach handles \`acme-inc\` (108k) cleanly per Sam's check.

## Related issues

- PLAT-4472 — "Download as CSV" button in admin UI (Priya, blocked on this)
- PLAT-4011 — Audit-log CSV export (Yusuf, 2025-11; the streaming template)
- PLAT-3987 — Per-column filtering in admin UI (parked)
- PLAT-3201 — Excel \`.xlsx\` export (parked, premium-tier)

## Comments

**ana@onramp.dev** · 2026-05-04T09:08:04Z
> Mostly happy-path. The streaming is the only non-obvious part — see
> investigation notes. \`big-tenant\` fixture in our test DB is what I
> used for the heap profiling above; reuse it for the regression test.

**lily@onramp.dev** · 2026-05-04T11:14:32Z
> Confirming Karen at midmarket-corp can't open BOM-less CSVs (her IT
> locked the Office config). The acme-inc export is the immediate
> need; ideally this is live before Friday's compliance deadline.

**sam@onramp.dev** · 2026-05-04T13:22:51Z
> Picking this up. Will swing through the full opchain pipeline.
> Plan: reuse the audit-log streaming pattern (PLAT-4011); add the
> RFC 4180 escaper as \`src/lib/csv.ts\`; one regression test against
> the \`big-tenant\` fixture asserting heap stays under 64MB.

**ana@onramp.dev** · 2026-05-04T13:31:09Z
> Sounds good. Ping me when staging is up — I'll have Karen open it
> on her Windows box before we ship to prod.

**sam@onramp.dev** · 2026-05-04T13:33:02Z
> Will do. Starting now.

## Activity log

\`\`\`
2026-05-01 16:42  ana@           created (Todo, P3, est 2)
2026-05-01 16:43  ana@           labeled "customer-success", "exports"
2026-05-02 09:14  lily@          added as watcher
2026-05-02 14:08  ana@           linked PLAT-4472 (blocked-by)
2026-05-03 10:02  ana@           added investigation notes
2026-05-03 16:30  lily@          commented (BOM requirement)
2026-05-04 09:08  ana@           updated description (added technical context)
2026-05-04 13:22  sam@           assigned self
2026-05-04 13:22  sam@           added label "opchain", "agent-driven"
2026-05-04 13:23  sam@           added to cycle 2026-W19
2026-05-04 13:33  sam@           commented (starting now)
\`\`\`

Checkpoint reference for this ticket (after pipeline run):
\`.checkpoints/app-architect.checkpoint.json\` → \`tickets.PLAT-4471\`.
`,
    },
    {
      id: "linked-pr",
      label: "PR #2208 description — auto-shaped from PLAT-4471",
      kind: "pr.md",
      body:
`# feat(api): add CSV export to /api/customers

> Auto-generated by opchain git-ops v1.2 from Linear ticket
> [PLAT-4471](https://linear.app/onramp/issue/PLAT-4471).
> Branch: \`feat/PLAT-4471-add-csv-export-customers\` · Base: \`main\` · SHA: \`7ea6bf2\`

**Linked ticket:** [PLAT-4471 — Add CSV export to /api/customers](https://linear.app/onramp/issue/PLAT-4471)
**Reviewers requested:** @yusuf (CSV streaming pattern owner), @priya (admin-UI consumer, PLAT-4472)
**Labels:** \`opchain\`, \`agent-driven\`, \`area:api\`, \`size:S\`

## Summary

Adds \`GET /api/customers.csv\` returning RFC 4180 CSV. Streams row-by-row
through the existing tenant-scoped query, respects the same filters
(\`?status=&plan=&q=\`), prefixes a UTF-8 BOM for Excel-on-Windows
compatibility, and downloads as \`customers-{tenant-slug}-{yyyy-mm-dd}.csv\`.

## Why

Customer Success uses the customer list daily and copy-pastes into Sheets.
Past ~50 rows that flow falls apart; \`acme-inc\`'s compliance team needed
108k rows last week. Lily flagged this as a top-3 CS productivity blocker
in Q2 planning (see PLAT-4471 description). UI button is PLAT-4472, which
this PR unblocks.

## How

Three new files; one modified.

### Files changed

| File | Lines | Purpose |
|---|---:|---|
| \`src/api/customers.csv.ts\` | +64 | New handler. Reuses \`getCustomersForTenant\` with a new \`stream: true\` option. |
| \`src/lib/csv.ts\` | +78 | RFC 4180 escaper + \`Response\` wrapping a \`ReadableStream\`. |
| \`src/services/customers.ts\` | +14 / -2 | Adds streaming cursor variant. JSON path unchanged. |
| \`tests/api/customers.csv.spec.ts\` | +194 | 7 new tests; see Test plan. |
| \`tests/fixtures/big-tenant.sql\` | (no diff) | Existing 108k-row fixture; reused for the heap-regression test. |

### Streaming approach

Reused the pattern from \`src/api/audit-log.csv.ts\` (PLAT-4011, Yusuf,
2025-11). The handler returns a \`Response\` wrapping a \`ReadableStream\`
that pulls rows from a Postgres cursor batch-by-batch (200 rows per batch,
matching the JSON endpoint's default).

Key excerpt:

\`\`\`ts
// src/api/customers.csv.ts (abbreviated)
export const GET = requireTenant(async ({ tenant, query }) => {
  const filters = customersFilterSchema.parse(query);
  const stream = new ReadableStream({
    async start(controller) {
      controller.enqueue(BOM);
      controller.enqueue(csvHeader(CUSTOMER_COLUMNS));
      for await (const row of getCustomersForTenant({
        tenantId: tenant.id, filters, stream: true,
      })) {
        controller.enqueue(csvRow(CUSTOMER_COLUMNS, row));
      }
      controller.close();
    },
  });
  return new Response(stream, {
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition":
        \`attachment; filename="customers-\${tenant.slug}-\${ymd()}.csv"\`,
    },
  });
});
\`\`\`

## Test plan

All 7 new tests pass (verified by Evaluator round 1):

- [x] **happy-path-200** — returns 200 + \`text/csv; charset=utf-8\` + filename header.
- [x] **filters-narrow-rows** — \`?status=active&plan=enterprise\` returns the expected subset.
- [x] **bom-prefix-present** — first 3 bytes are \`EF BB BF\`; verified via \`xxd\` and via opening the file in a Sheets fixture.
- [x] **rfc4180-escaping** — values containing commas, double-quotes, CR, LF round-trip correctly through the escaper.
- [x] **auth-401-unauthenticated** — request without auth returns 401, no body leak.
- [x] **auth-403-cross-tenant** — request authenticated as tenant A asking for tenant B returns 403.
- [x] **stream-big-tenant-heap-bounded** — streams 108,442 rows from \`big-tenant\` fixture; heap p95 stays under 64MB (asserted via \`process.memoryUsage().heapUsed\` sampling).

Run: \`vitest run tests/api/customers.csv.spec.ts\` (passes in 8.3s locally; CI parity).

## Performance

Benchmarked against \`big-tenant\` (108,442 rows) on staging using a local
\`wrk\` harness:

| Metric | JSON endpoint (current) | CSV endpoint (this PR) |
|---|---:|---:|
| Wall-clock to last byte | 4.1s | 3.2s |
| Heap p95 | 622 MB | 38 MB |
| Heap peak | 681 MB | 41 MB |
| First byte | 380 ms | 41 ms |
| Worker CPU time | 2.8s | 2.1s |

The streaming variant is **~16× more memory-efficient** for this tenant
and starts emitting bytes ~9× sooner, which matters for CS workflows
(they often abort downloads partway through if the wrong filter was
applied).

## Sample transactions

\`\`\`
$ curl -s -H 'Authorization: Bearer ...' \\
    'https://staging.api.onramp.dev/api/customers.csv?status=active&plan=enterprise' \\
    | head -3 | xxd | head -5
00000000: efbb bf69 642c 6e61 6d65 2c65 6d61 696c  ...id,name,email
00000010: 2c70 6c61 6e2c 7374 6174 7573 2c6d 7272  ,plan,status,mrr
00000020: 5f63 656e 7473 2c63 7265 6174 6564 5f61  _cents,created_a
00000030: 742c 6c61 7374 5f61 6374 6976 655f 6174  t,last_active_at
00000040: 0a63 7573 5f30 312c 2241 636d 6520 4865  .cus_01,"Acme He
\`\`\`

Confirms BOM, header order, RFC 4180 quoting on the name field.

## Rollout

- **Feature flag:** none. New endpoint, no existing behaviour to gate.
- **Monitoring:** new dashboard panel on the \`api/customers\` dashboard:
  p95 latency + heap peak per request, tagged \`endpoint=customers.csv\`.
  Alert added: \`customers_csv_p95_latency_high\` (p95 > 1.5s for 5min,
  SEV-3).
- **Deploy order:** standard. staging → prod via deploy-ops gate.
  No coordinated deploy needed; PLAT-4472 (UI button) can ship anytime
  after this lands.

## Reviewer guide

If you're short on time:

1. Read \`src/lib/csv.ts\` first — the RFC 4180 escaper is the only
   non-obvious code. ~80 LOC.
2. Then \`src/api/customers.csv.ts\` — handler is ~60 LOC.
3. Then the \`stream-big-tenant-heap-bounded\` test (lines 142-189 of
   the spec) — it's the regression that asserts we don't OOM.
4. Skip the snapshot-fixture diff and the per-column escaping tests
   unless you want to double-check RFC 4180 quote-handling edge cases.

## Audit gate

- [x] **code-auditor /audit pre-deploy:** Grade A. 0 blocking findings;
      1 advisory ("csv.ts could be ~30 LOC shorter using a generator;
      not blocking"). Full output in PLAT-4471 comments.
- [x] **bug-check pre-commit:** PASS (1.4s). Type, lint, build,
      dep-audit, secret-scan all clean.
- [x] **Unit tests:** 7 new, 0 changed, 0 deleted. 147 → 154 total.
- [x] **Integration test:** \`big-tenant\` fixture (108k rows) — heap
      stable at 38 MB p95 (asserted in test).

## Out of scope (PLAT-4472 / -3201 / -3987 own)

- The "Download as CSV" UI button (PLAT-4472).
- Excel-native \`.xlsx\` export (PLAT-3201, parked).
- Per-column filtering UI (PLAT-3987, parked).
- Background-job CSV for tenants > 500k customers — not needed at
  current size; revisit if a tenant approaches that bound.

---

Refs: PLAT-4471 · Sprint plan: Linear PLAT-4471/sprint-1 · Auditor: A · bug-check: PASS

🤖 Generated with opchain git-ops v1.2.
`,
    },
    {
      id: "deploy-ticket",
      label: "PLAT-4485 — auto-created deploy ticket",
      kind: "linear.md",
      body:
`# PLAT-4485 — Deploy: 2026-05-04 · staging → prod (1 ticket)

**URL:** https://linear.app/onramp/issue/PLAT-4485
**Project:** Platform · **Type:** Deploy · **State:** Shipped · **Priority:** Medium (auto) · **Estimate:** — (auto-created)
**Reporter:** opchain-deploy-ops (bot) · **Assignee:** sam@onramp.dev · **Parent:** [PLAT-4471](https://linear.app/onramp/issue/PLAT-4471)
**Labels:** \`opchain\`, \`agent-driven\`, \`deploy\`, \`environment:prod\`
**Watchers:** sam@onramp.dev, ops-rotation@onramp.dev
**Created:** 2026-05-04T14:02:11Z · **Closed:** 2026-05-04T14:11:02Z (duration 8m 51s)

## Description

Auto-generated by opchain deploy-ops v1.2.

\`\`\`
Environment:     prod (via staging)
Commit range:    a8a254c..7ea6bf2  (2 commits)
Linked tickets:  PLAT-4471 (1)
Audit gate:      PASS — code-auditor Grade A; security-auditor PASS; bug-check PASS
Migrations:      0 (none in range)
Env / config:    0 changes
Dependencies:    0 added, 0 removed, 0 updated
Risk band:       LOW (additive endpoint; no existing surface modified)
\`\`\`

## Commit range

| SHA | Subject | Author | Ticket refs |
|---|---|---|---|
| \`7ea6bf2\` | feat(api): add CSV export to /api/customers | sam@ | PLAT-4471 |
| \`a8a254c\` | chore(deps): drop unused \`@types/csv-stringify\` | dependabot | — |

## Migrations applied

None. (No SQL files in \`db/migrations/\` are new in this range.)

## Env / config changes

None.

## Dependencies

\`\`\`
npm diff --against a8a254c..7ea6bf2 -- package-lock.json
removed: @types/csv-stringify@3.1.1 (unused; not imported anywhere)
\`\`\`

No runtime dependency changes.

## Audit gate output (verbatim)

\`\`\`
[code-auditor /audit pre-deploy]
  Files reviewed:    3 (src/api/customers.csv.ts, src/lib/csv.ts, src/services/customers.ts)
  Findings:          0 blocking, 1 advisory
  Advisory #1:       csv.ts could be ~30 LOC shorter using a generator (advisory only)
  Tests:             7 new, 147 existing, 0 failing
  Coverage:          new code 100% line, 100% branch
  Type-check:        PASS
  Lint:              PASS
  Grade:             A
  Wall-clock:        12.4s

[security-auditor /sec verify]
  Threat-model scope: api endpoints
  STRIDE findings:    0 new
  Rate-limit:         inherited from /api/customers (60/min anon, 600/min auth)
  CSP impact:         none (no new third-party resources)
  Verdict:            PASS

[bug-check pre-commit]
  Type:               PASS
  Lint:               PASS
  Build:              PASS (worker bundle 487KB; budget 600KB)
  Dep-audit:          PASS (0 vulns)
  Secret-scan:        PASS
  Wall-clock:         1.4s
\`\`\`

## Smoke tests (staging)

\`\`\`
$ curl -fsS https://staging.api.onramp.dev/api/health | jq '.version'
"7ea6bf2"
  → PASS

$ curl -fsS -H 'Authorization: Bearer ...' \\
    'https://staging.api.onramp.dev/api/customers?limit=3' | jq '.data | length'
3
  → PASS (existing endpoint unaffected)

$ curl -fsS -H 'Authorization: Bearer ...' \\
    'https://staging.api.onramp.dev/api/customers.csv?status=active' \\
    -D - | head -5
HTTP/2 200
content-type: text/csv; charset=utf-8
content-disposition: attachment; filename="customers-onramp-2026-05-04.csv"
x-opchain-version: 7ea6bf2
  → PASS

$ curl -fsS -H 'Authorization: Bearer ...' \\
    'https://staging.api.onramp.dev/api/customers.csv' | head -c 3 | xxd
00000000: efbb bf                                  ...
  → PASS (BOM present)

$ curl -fsS https://staging.api.onramp.dev/api/customers.csv
  → 401 (unauthenticated path)
  → PASS

All 5 smoke checks PASS. Staging deploy verified.
\`\`\`

## Watch list (post-deploy)

| Dashboard / Alert | URL | Why |
|---|---|---|
| \`api/customers\` p99 latency | https://app.datadoghq.com/dashboard/onramp-api | New endpoint shares the same service pool; watch for noisy-neighbor effects |
| \`customers_csv_p95_latency_high\` alert | (new this deploy) | Threshold 1.5s p95 for 5min; SEV-3 routing to PLAT-BACKEND |
| Worker heap p95 | https://dash.cloudflare.com/.../worker-analytics | Heap budget 128MB; the streaming endpoint stays around 38MB but watch for drift |
| Sentry — \`csv\` tag | https://sentry.io/onramp/issues/?query=is:unresolved+tag:csv | Any uncaught exception in the CSV path |
| Linear cycle 2026-W19 throughput | https://linear.app/onramp/cycle/2026-W19 | Confirm this didn't slip the cycle |

## Rollback plan

If post-deploy regression observed within 30 minutes:

\`\`\`bash
# 1. Find the prior good deployment
npx wrangler deployments list | head -5
# 2. Revert (typical revert window <60s globally)
npx wrangler rollback <prior-deployment-id>
# 3. Confirm
curl -fsS https://api.onramp.dev/api/health | jq '.version'   # should equal a8a254c
\`\`\`

The change is additive (new endpoint; no shared code paths modified
beyond the small \`getCustomersForTenant\` streaming option). Rollback is
safe; no data migration to reverse.

## Timeline (UTC)

\`\`\`
14:02:11  deploy-ops invoked /deploy staging               state: in_progress
14:02:11  audit gate verified (cached from /git-sync)
14:02:13  wrangler deploy --env staging                    start
14:02:48  wrangler deploy --env staging                    success (37s)
14:02:48  staging smoke tests began
14:03:02  staging smoke tests passed (5/5)                  → state: staging_verified
14:03:03  monitoring-ops notified: /watch staging.api.onramp.dev
14:03:04  Linear ticket PLAT-4471 commented (staging shipped)
14:09:30  human approval received (sam@)                    → ready for prod
14:09:51  wrangler deploy (prod)                            start
14:10:33  wrangler deploy (prod)                            success (42s)
14:10:33  prod smoke tests began
14:10:51  prod smoke tests passed (5/5)
14:11:02  /api/health prod returns X-Opchain-Version: 7ea6bf2 → state: shipped
14:11:02  Linked tickets transitioned: PLAT-4471 → Done
14:11:14  monitoring-ops attached: /watch api.onramp.dev (30-min sentinel)
\`\`\`

## Comments

**opchain-deploy-ops** · 14:02:13Z
> Auto-created from \`/deploy staging\`. Audit gate clean (Grade A).
> 1 deploy-relevant commit; 1 linked ticket. Staging deploy beginning.

**opchain-deploy-ops** · 14:03:02Z
> Smoke tests PASS against staging.api.onramp.dev. Audit gate green.
> Awaiting human approval for prod.

**sam@onramp.dev** · 14:08:42Z
> Pinged ana — she had Karen verify the staging CSV opens cleanly in
> Excel-on-Windows (BOM present, no corrupted glyphs). Approving prod.

**opchain-deploy-ops** · 14:09:51Z
> Prod deploy beginning (range \`a8a254c..7ea6bf2\`).

**opchain-deploy-ops** · 14:10:51Z
> Prod deployed: \`7ea6bf2\`. Smoke tests 5/5. Linked tickets transitioned
> to "Done" with the prod URL.

**sam@onramp.dev** · 14:11:14Z
> Looks clean. Watching dashboards for the next 30 min.

**opchain-monitoring-ops** · 14:42:19Z
> 30-min post-deploy sentinel complete. No anomalies on
> \`api/customers\` dashboard. p99 latency steady ~120ms across both
> JSON and CSV variants. Heap p95 well within budget. No
> \`customers_csv_p95_latency_high\` fires. Linking sentinel report
> in the next thread comment.

## Linked

- parent: [PLAT-4471 — Add CSV export to /api/customers](https://linear.app/onramp/issue/PLAT-4471)
- pull-request: https://github.com/onramp-inc/platform/pull/2208 (merged)
- monitoring-sentinel: \`.checkpoints/monitoring-ops.checkpoint.json#sentinels.PLAT-4485\`
`,
    },
    {
      id: "incident-ticket",
      label: "PLAT-4503 — auto-opened incident ticket (next morning)",
      kind: "linear.md",
      body:
`# PLAT-4503 — Incident: customers.csv p95 latency · 2026-05-05 09:14 UTC

**URL:** https://linear.app/onramp/issue/PLAT-4503
**Project:** Platform · **Type:** Incident · **Severity:** SEV-3 · **State:** Resolved (PM pending) → Done
**Priority:** Urgent (auto-set by monitoring-ops for any incident ticket) · **Reporter:** opchain-monitoring-ops (bot) · **Assignee:** sam@onramp.dev (on-call)
**Parent:** [PLAT-4485](https://linear.app/onramp/issue/PLAT-4485) (caused-by: deploy 18h prior)
**Labels:** \`opchain\`, \`agent-driven\`, \`incident\`, \`service:api/customers.csv\`, \`severity:SEV-3\`, \`postmortem-required\`
**Watchers:** sam@onramp.dev, ops-rotation@onramp.dev, lily@onramp.dev (CS impact)
**Created:** 2026-05-05T09:14:33Z · **Resolved:** 2026-05-05T09:30:14Z (16 min) · **Closed:** 2026-05-05T11:48:14Z (postmortem complete)

## Description

Auto-generated by opchain monitoring-ops v1.2.

**Alert:** \`customers_csv_p95_latency_high\` (SEV-3)
**Fired at:** 2026-05-05T09:14:33Z
**Service:** \`api/customers.csv\` (new endpoint; shipped 18h prior in PLAT-4485)
**On-call:** sam@onramp.dev (PagerDuty escalation policy: EP-PLAT-BACKEND)
**Runbook:** https://runbooks.onramp.dev/api-latency-investigation
**Recent deploys (last 24h):**
- [PLAT-4485 — Deploy 2026-05-04 14:10:51Z](https://linear.app/onramp/issue/PLAT-4485) — included PLAT-4471 (\`/api/customers.csv\`) ← **most likely culprit**

**Likely culprit:** the deploy 18h ago is the most recent change touching
this surface. The alert fires on the new endpoint specifically.

## Alert payload (verbatim from PagerDuty)

\`\`\`json
{
  "incident_id": "PD-INC-018347",
  "incident_key": "customers_csv_p95_latency_high:api/customers.csv",
  "service": {
    "id": "PS-PLAT-BACKEND",
    "name": "api/customers"
  },
  "urgency": "high",
  "severity": "warning",
  "status": "triggered",
  "created_at": "2026-05-05T09:14:33Z",
  "description": "customers_csv_p95_latency_high triggered on api/customers.csv",
  "details": {
    "metric": "request_duration_p95",
    "endpoint": "/api/customers.csv",
    "p95_observed_ms": 4218,
    "p95_threshold_ms": 1500,
    "p99_observed_ms": 11833,
    "p99_threshold_ms": 5000,
    "window_seconds": 300,
    "request_count_in_window": 142,
    "error_rate": 0.0,
    "tenant_breakdown": {
      "acme-inc": { "requests": 89, "p95_ms": 5810 },
      "midmarket-corp": { "requests": 31, "p95_ms": 2440 },
      "other": { "requests": 22, "p95_ms": 980 }
    }
  },
  "links": [
    { "name": "Dashboard", "href": "https://app.datadoghq.com/.../onramp-api" },
    { "name": "Runbook", "href": "https://runbooks.onramp.dev/api-latency-investigation" }
  ]
}
\`\`\`

## Dashboards (described)

### \`api/customers\` p95 latency (last 1h)

Graph shows the \`/api/customers.csv\` endpoint p95 latency stepping from
~140ms steady-state (overnight, 03:00-09:00Z) up to **4.2s** beginning at
09:11:18Z, with a sharp inflection — not a gradual rise. By 09:14 the
5-min window p95 had crossed the 1.5s threshold and held there.
\`/api/customers\` (JSON variant) is unchanged at ~120ms p95 across the
same window.

### Request volume (last 1h)

Volume on \`/api/customers.csv\` jumped from ~2 req/min (overnight) to ~30
req/min at 09:11Z — coincides with acme-inc's CS team starting their
morning batch (one user, sequential downloads of filtered slices). Not
the alert cause; just context.

### Worker heap p95

Heap p95 on the worker pool serving the endpoint climbed from 38MB
(baseline post-deploy) to **97MB** during the window. Headroom shrunk
but no OOM — the budget is 128MB.

## Symptoms (top 5)

- p95 latency: **4.2s** (threshold 1.5s) — **+200% over budget**
- p99 latency: **11.8s** (threshold 5.0s) — **+136% over budget**
- p50 latency: 850ms (no fixed threshold; baseline ~80ms — **10× elevated**)
- error rate: **0.0%** (no errors, just slow — points away from a 5xx-class bug)
- request rate: ~30 req/min (vs ~2 baseline — driven by acme-inc CS morning batch)

## Investigation (sam — 09:18Z)

Bisecting:

1. \`/api/customers\` JSON variant: unaffected, p95 ~120ms. → Suggests the regression is in the streaming path, not in shared code.
2. PR #2208 (PLAT-4471) is the only change touching this surface in the deploy. → Confirms PLAT-4485 as the likely culprit.
3. Heap is elevated but not the OOM regime. Implies a per-request cost that scales with row count and isn't getting freed promptly.
4. acme-inc (108k rows) drives 89/142 requests in the window with p95 5.8s; midmarket-corp (~3k rows) is 31/142 at 2.4s p95. → Linear correlation with row count.

## What I tried

- 09:18Z: ran \`EXPLAIN ANALYZE\` for the cursor query against acme-inc. Plan looks fine — index used, bounded buffer.
- 09:21Z: added a \`console.time\` log line to the inner generator loop in staging via \`wrangler tail\`. Saw a **per-row roundtrip cost of ~50ms**. Should be near-zero in a streaming cursor.
- 09:24Z: pulled the audit-log CSV streaming code (PLAT-4011 reference). Spotted the diff: the audit-log path uses \`pg.cursor.read(N)\` with batch size 200. **My CSV path is calling \`pg.cursor.read(1)\` because I forgot the batch arg.** Each row = one network roundtrip to Postgres.

## Root cause

\`getCustomersForTenant({ stream: true })\` opens a Postgres cursor but
reads from it one row at a time via \`cursor.read(1)\`. The implicit
\`cursor.read()\` default is 1 (not the 200 we assumed). For acme-inc's
108k rows, that's 108k Postgres roundtrips per request at ~50ms each —
a 90-minute response in theory; in practice the worker times out
around 30s and the user sees an aborted download.

**The fix is one line:** \`cursor.read(BATCH_SIZE)\` where \`BATCH_SIZE = 200\`,
matching the audit-log pattern.

## Timeline (UTC)

\`\`\`
09:11:18  /api/customers.csv p95 begins climbing
09:11:30  acme-inc CS user starts morning batch (kicks off the volume that exposes the regression)
09:14:33  alert customers_csv_p95_latency_high fires
09:14:34  PagerDuty creates incident PD-INC-018347
09:14:34  monitoring-ops creates PLAT-4503; parent=PLAT-4485
09:14:35  monitoring-ops pages sam (on-call)
09:14:35  monitoring-ops comments to PLAT-4485 (caused-by linkage)
09:15:11  sam ack via PagerDuty (auto-mirrored to PLAT-4503)
09:15:30  sam opens runbook + dashboard
09:18:04  sam isolates regression to the streaming path
09:21:46  sam adds wrangler tail probe; observes per-row 50ms cost
09:24:08  sam identifies the cursor.read() default bug
09:25:00  sam drafts the one-line fix
09:25:30  sam runs /git-sync; PR #2211 opens
09:27:40  /audit pre-deploy Grade A; bug-check PASS
09:28:50  /deploy staging — 33s
09:29:30  staging smoke (with acme-inc fixture) — p95 78ms ✓
09:30:00  /deploy prod (approved) — 41s
09:30:14  prod traffic resumes normal latency; alert auto-resolves
09:30:14  monitoring-ops auto-resolved comment posted
09:30:30  monitoring-ops transitions PLAT-4503 → Resolved (PM pending)
09:32:00  monitoring-ops attaches /watch sentinel (30 min)
10:02:14  sentinel complete; no recurrence
11:48:00  sam publishes postmortem doc; remediation sub-tickets created
11:48:14  monitoring-ops transitions PLAT-4503 → Done
\`\`\`

## MTTR breakdown

| Phase | Window | Duration |
|---|---|---:|
| Detect | 09:11:18 (first elevation) → 09:14:33 (alert fires) | 3m 15s |
| Acknowledge | 09:14:33 → 09:15:11 (PagerDuty ack) | 38s |
| Diagnose | 09:15:11 → 09:24:08 (root cause identified) | 8m 57s |
| Mitigate / fix | 09:24:08 → 09:30:14 (resolved in prod) | 6m 06s |
| **Total time-to-resolution** | 09:11:18 → 09:30:14 | **18m 56s** |
| (Time-to-resolution from alert) | 09:14:33 → 09:30:14 | **15m 41s** |

## Customer impact

- **acme-inc** — 89 attempted downloads in the window; estimate ~12 unique CS users affected; observed timeouts on 6 of them (the rest got partial files / browser-aborted). **Direct impact.**
- **midmarket-corp** — 31 requests; observed slow but no timeouts. **Minor impact.**
- **Other tenants** — 22 requests across ~8 tenants; users may have noticed slowness on filtered slices > 5k rows. **Negligible impact.**

No customer-facing communication was sent (per status-page policy:
SEV-3 with < 30 min impact does not page the comms team). lily@ was
DM'd at 09:32 with a summary; she relayed an internal "fix is out" to
the affected CS users at 09:36.

## Status page

Not posted. SEV-3 internal alert, < 30 min duration, < 1% of total
traffic affected. Documented for postmortem reference.

## Comments (auto + human)

**opchain-monitoring-ops** · 09:14:34Z
> Alert \`customers_csv_p95_latency_high\` fired (SEV-3). Most recent
> deploy: PLAT-4485 (PLAT-4471, customers.csv shipped 18h ago).
> Paging on-call: sam@onramp.dev. Runbook:
> https://runbooks.onramp.dev/api-latency-investigation

**sam@onramp.dev** *(via PagerDuty)* · 09:15:11Z
> Acknowledged. Pulling up dashboards.

**sam@onramp.dev** · 09:18:04Z
> Confirmed: \`/api/customers\` JSON variant is unaffected. Regression
> is in the streaming path specifically. Probably PR #2208.

**sam@onramp.dev** · 09:24:08Z
> Found it. \`cursor.read()\` defaults to 1 row per call; we needed
> \`cursor.read(200)\`. Per-row Postgres roundtrip for 108k rows = 90
> min in theory. One-line fix incoming.

**opchain-monitoring-ops** · 09:30:14Z
> Alert auto-resolved (back to baseline). Impact duration: ~16 min.
> Transitioning PLAT-4503 to \`Resolved (PM pending)\`. Postmortem
> required (sub-issue auto-created: PLAT-4503/postmortem).

**sam@onramp.dev** · 11:48:00Z
> Postmortem published:
> https://docs.onramp.dev/postmortems/2026-05-05-customers-csv-latency.
> Action items filed as sub-tickets (see Sub-tickets section).
> Closing.

**opchain-monitoring-ops** · 11:48:14Z
> Postmortem present and reviewed. Transitioning to \`Done\`.

## Sub-tickets (auto-created remediation)

| Ticket | Title | Owner | Due | Priority |
|---|---|---|---|---|
| [PLAT-4504](https://linear.app/onramp/issue/PLAT-4504) | Fix Postgres cursor to use BATCH_SIZE read | sam | 2026-05-05 (✓ done) | High |
| [PLAT-4505](https://linear.app/onramp/issue/PLAT-4505) | Add p95 800ms warn alert tier (catches before SEV-3) | vee | 2026-05-08 | Medium |
| [PLAT-4506](https://linear.app/onramp/issue/PLAT-4506) | Add big-tenant CSV load test to CI on every PR | yusuf | 2026-05-12 | Medium |
| [PLAT-4507](https://linear.app/onramp/issue/PLAT-4507) | Document cursor.read() default in services-style-guide | priya | 2026-05-19 | Low |

## Lessons

- **What we'd do differently:** the regression test for streaming heap
  bounded should have been a regression test for streaming **throughput**
  too. Heap was fine; latency wasn't covered. PLAT-4506 closes this.
- **What surprised us:** \`pg.cursor.read()\` defaulting to 1 row is
  reasonable for some workloads but counter-intuitive for streaming.
  The audit-log code (PLAT-4011) got it right; reviewing one pattern
  reference is not the same as reading the docs. PLAT-4507 closes this.
- **What worked well:** end-to-end time from alert to prod fix was
  ~16 minutes. The opchain pipeline (PR → audit → staging → prod
  with the same gates as any other deploy) didn't slow this down;
  it actually sped it up because the cached audit gate from /git-sync
  meant we didn't re-run the suite.

## Linked

- caused-by: [PLAT-4471 — Add CSV export to /api/customers](https://linear.app/onramp/issue/PLAT-4471)
- triggered-from: [PLAT-4485 — Deploy 2026-05-04](https://linear.app/onramp/issue/PLAT-4485)
- fix-deployed-in: [PLAT-4486 — Deploy 2026-05-05](https://linear.app/onramp/issue/PLAT-4486)
- postmortem: https://docs.onramp.dev/postmortems/2026-05-05-customers-csv-latency
- follow-up-of: [PLAT-4011 — Audit-log CSV export](https://linear.app/onramp/issue/PLAT-4011) (the pattern we should have copied exactly)

Checkpoint: \`.checkpoints/monitoring-ops.checkpoint.json\` → \`incidents.PLAT-4503\`.
`,
    },
    {
      id: "end-to-end-trace",
      label: "Linear timeline — the full thread",
      kind: "trace.md",
      body:
`# PLAT-4471 — Linear timeline (across the v1.2 pipeline)

**Produced by** the cross-skill audit trace · **Method:** chronological union of every comment / state change / linked-ticket event across PLAT-4471, PLAT-4485, PLAT-4503, PLAT-4504-4507 · **Window:** 2026-05-01 → 2026-05-05

A single human-readable view of every state change, comment, and
linked-ticket creation between Linear and the opchain skills, top to
bottom. This is what the audit log looks like to a curious team member
two weeks later — and what an auditor sees if they ask "show me every
agent-driven event tied to PLAT-4471."

## Timeline

\`\`\`
day -3 (2026-05-01)
  16:42  ana          PLAT-4471 created (Todo, Medium, est 2)              checkpoint: —
  16:43  ana          PLAT-4471 labeled "customer-success", "exports"      checkpoint: —

day -1 (2026-05-03)
  10:02  ana          PLAT-4471 #comment "Mostly just a happy-path…"        checkpoint: —
  16:30  lily         PLAT-4471 #comment (BOM requirement)                  checkpoint: —

day 0 (2026-05-04)
  13:22  sam          PLAT-4471 self-assigned                              checkpoint: —
  13:22  sam          PLAT-4471 labeled "opchain", "agent-driven"          checkpoint: —
  13:22  sam          PLAT-4471 added to cycle 2026-W19                    checkpoint: —
  13:33  sam          PLAT-4471 #comment "Picking this up..."              checkpoint: —

  -- engineer prompt: "/discover --ticket PLAT-4471"
  13:35  app-architect   MCP linear.get_issue("PLAT-4471")                 checkpoint: app-architect/discover.ticket
  13:35  app-architect   /discover ran (8 questions, 5 pre-filled)         checkpoint: app-architect/discover
  13:38  app-architect   /spec produced (1 file: existing project)         checkpoint: app-architect/spec
  13:39  app-architect   /roadmap produced (1 sprint, 1 deliverable)       checkpoint: app-architect/roadmap

  -- engineer confirms streaming approach
  13:42  app-architect   read src/services/customers.ts (getCustomersForTenant signature)  checkpoint: —
  13:43  app-architect   MCP linear.add_comment("PLAT-4471", "Sprint 1...")  checkpoint: app-architect/sprint-comment-posted
  13:43  app-architect   MCP linear.create_issue (sub-issue, parent=PLAT-4471) → PLAT-4471/sprint-1  checkpoint: app-architect/sprint-1-child
  13:44  app-architect   /build started                                    checkpoint: app-architect/build.in-progress
  13:46  app-architect   Generator wrote handler + helper + tests          checkpoint: app-architect/build.generator-r1
  13:47  app-architect   Evaluator round 1: PASS (9, 9, 8, n/a)            checkpoint: app-architect/build.evaluator-r1

  -- engineer confirms with staging benchmark
  13:50  app-architect   ran heap benchmark against big-tenant fixture     checkpoint: app-architect/benchmark.big-tenant
  13:51  app-architect   reported 38MB heap p95 (vs 622MB on JSON path)    checkpoint: —

  -- engineer prompt: "/git-sync"
  13:55  git-ops      MCP linear.get_issue("PLAT-4471")  (refresh)          checkpoint: git-ops/sync.read
  13:55  git-ops      branch: feat/PLAT-4471-add-csv-export-customers      checkpoint: git-ops/branch-created
  13:56  git-ops      commit: feat(api): add CSV export… Refs: PLAT-4471   checkpoint: git-ops/commit-signed
  13:57  git-ops      PR opened (gh): #2208                                checkpoint: git-ops/pr-opened.#2208
  13:57  git-ops      MCP linear.add_comment("PLAT-4471", "PR opened: …")  checkpoint: git-ops/pr-comment-posted
  13:57  git-ops      MCP linear.save_issue("PLAT-4471", state="In Review") checkpoint: git-ops/state-transitioned

  13:58  bug-check    PASS (1.4s)                                          checkpoint: bug-check/precommit.pass
  13:58  code-auditor /audit pre-deploy                                    checkpoint: code-auditor/pre-deploy.in-progress
  14:00  code-auditor MCP linear.add_comment("PLAT-4471", "Auditor: Grade A; 0 blocking, 1 advisory")  checkpoint: code-auditor/pre-deploy.posted

  -- 14:02:11Z
  14:02  deploy-ops   /deploy staging                                      checkpoint: deploy-ops/deploy.start
  14:02  deploy-ops   MCP linear.create_issue ("Deploy 2026-05-04 ...") → PLAT-4485  checkpoint: deploy-ops/deploy-ticket.PLAT-4485
  14:02  deploy-ops   staging deploy started                               checkpoint: deploy-ops/staging.in-flight
  14:02  deploy-ops   staging deploy succeeded (37s)                       checkpoint: deploy-ops/staging.complete
  14:03  deploy-ops   smoke tests passed (5/5)                             checkpoint: deploy-ops/staging.smoke-pass
  14:03  deploy-ops   MCP linear.add_comment("PLAT-4485", "Smoke tests passed…") checkpoint: deploy-ops/staging-verified.posted
  14:03  deploy-ops   MCP linear.save_issue("PLAT-4485", state="Staging verified") checkpoint: deploy-ops/staging-verified.transitioned

  -- 14:08-14:09Z human verification
  14:08  sam          DM to ana: "staging up; have Karen verify?"          checkpoint: —
  14:09  ana          replied: "Karen confirms BOM works"                   checkpoint: —

  -- 14:09:30Z
  14:09  sam          /deploy prod (approved)                              checkpoint: deploy-ops/prod.approval-received
  14:09  deploy-ops   prod deploy started                                  checkpoint: deploy-ops/prod.in-flight
  14:10  deploy-ops   prod deploy succeeded (42s)                          checkpoint: deploy-ops/prod.complete
  14:10  deploy-ops   smoke tests passed (5/5)                             checkpoint: deploy-ops/prod.smoke-pass
  14:11  deploy-ops   MCP linear.add_comment("PLAT-4485", "Prod deployed: 7ea6bf2…") checkpoint: deploy-ops/prod-shipped.posted
  14:11  deploy-ops   MCP linear.save_issue("PLAT-4485", state="Shipped")  checkpoint: deploy-ops/prod-shipped.transitioned
  14:11  deploy-ops   MCP linear.add_comment("PLAT-4471", "Shipped to prod via PLAT-4485.") checkpoint: deploy-ops/linked-shipped.posted
  14:11  deploy-ops   MCP linear.save_issue("PLAT-4471", state="Done")     checkpoint: deploy-ops/source-done.transitioned

  -- 30-min sentinel
  14:11  monitoring-ops /watch api.onramp.dev (30 min)                     checkpoint: monitoring-ops/sentinel.PLAT-4485
  14:42  monitoring-ops sentinel clean; no anomalies                       checkpoint: monitoring-ops/sentinel.PLAT-4485.complete
  14:42  monitoring-ops MCP linear.add_comment("PLAT-4485", "30-min post-deploy sentinel…")  checkpoint: monitoring-ops/sentinel-comment.posted

day +1 (2026-05-05, next morning)
  -- 09:11:18Z first latency elevation observed
  -- 09:14:33Z alert fires
  09:14  monitoring-ops alert "customers_csv_p95_latency_high" SEV-3       checkpoint: monitoring-ops/alert.fired
  09:14  monitoring-ops MCP linear.create_issue (Incident, parent=PLAT-4485) → PLAT-4503  checkpoint: monitoring-ops/incident.PLAT-4503
  09:14  monitoring-ops PagerDuty page → sam                               checkpoint: monitoring-ops/pagerduty.paged

  -- 09:15:11
  09:15  sam            ack via PagerDuty (auto-mirrored to PLAT-4503)     checkpoint: monitoring-ops/incident.acked
  09:18  sam            isolated regression to streaming path              checkpoint: —
  09:24  sam            identified cursor.read() default bug               checkpoint: —
  09:25  sam            /git-sync (one-line fix)                           checkpoint: git-ops/sync.PLAT-4503-fix
  09:27  code-auditor   /audit pre-deploy: Grade A                         checkpoint: code-auditor/PLAT-4503-fix.pass
  09:28  bug-check      PASS                                               checkpoint: bug-check/PLAT-4503-fix.pass
  09:28  deploy-ops     /deploy staging (33s, smoke pass)                  checkpoint: deploy-ops/PLAT-4503-fix.staging
  09:30  deploy-ops     /deploy prod (41s, smoke pass)                     checkpoint: deploy-ops/PLAT-4503-fix.prod

  -- 09:30:14 alert auto-resolves
  09:30  monitoring-ops MCP linear.add_comment("PLAT-4503", "Alert auto-resolved (16 min).") checkpoint: monitoring-ops/incident.auto-resolved.posted
  09:30  monitoring-ops MCP linear.save_issue("PLAT-4503", state="Resolved (PM pending)")    checkpoint: monitoring-ops/incident.transitioned

  -- 11:48:00 postmortem published
  11:48  sam            postmortem published                               checkpoint: monitoring-ops/postmortem.published
  11:48  monitoring-ops MCP linear.create_issue x4 (PLAT-4504..4507)       checkpoint: monitoring-ops/remediation.created
  11:48  monitoring-ops MCP linear.add_comment("PLAT-4503", "Postmortem published; 4 sub-tickets filed.") checkpoint: monitoring-ops/postmortem-comment.posted
  11:48  monitoring-ops MCP linear.save_issue("PLAT-4503", state="Done")   checkpoint: monitoring-ops/incident.done
\`\`\`

## What just happened

One ticket, one engineer, one calendar day from "I'll pick this up" to
"shipped"; one alert, sixteen minutes from fire to resolved, the next
morning. **Every agent-driven event lives in Linear under PLAT-4471's
thread (parent / child / linked).** A team member searching for
PLAT-4471 two weeks later sees the full audit trail without leaving the
PM tool. An auditor asking "what changed in the API on May 4-5, who
authorised it, and who responded when it broke" gets the same answer
from the same view.

## What you can grep for

Every agent-driven comment on Linear carries a stable HTML marker so a
re-run of any skill is a no-op rather than a duplicate post. Useful
greps for forensic review:

| Marker prefix | Skill | Meaning |
|---|---|---|
| \`<!-- opchain:app-architect:sprint-created:\` | app-architect | sprint child ticket created |
| \`<!-- opchain:git-ops:pr-opened:\` | git-ops | PR opened against this ticket |
| \`<!-- opchain:git-ops:pr-merged:\` | git-ops | PR merged for this ticket |
| \`<!-- opchain:code-auditor:audit-posted:\` | code-auditor | audit grade reported back |
| \`<!-- opchain:deploy-ops:deploy-created:\` | deploy-ops | deploy ticket created |
| \`<!-- opchain:deploy-ops:staging-verified:\` | deploy-ops | staging smoke passed |
| \`<!-- opchain:deploy-ops:prod-shipped:\` | deploy-ops | prod ship complete |
| \`<!-- opchain:deploy-ops:linked-shipped:\` | deploy-ops | linked source ticket transitioned to Done |
| \`<!-- opchain:monitoring-ops:incident-fired:\` | monitoring-ops | incident auto-opened |
| \`<!-- opchain:monitoring-ops:acked:\` | monitoring-ops | on-call acknowledged |
| \`<!-- opchain:monitoring-ops:auto-resolved:\` | monitoring-ops | alert auto-resolved |
| \`<!-- opchain:monitoring-ops:postmortem:\` | monitoring-ops | postmortem published |

## Replaying this session

A team member two weeks out who wants to reconstruct what happened:

1. **Linear search:** \`PLAT-4471\` opens the parent; the Linked Issues
   panel surfaces PLAT-4485, PLAT-4503, PLAT-4504-4507.
2. **Marker grep:** the markers above pin the agent-driven events; any
   human comment is interleaved by timestamp.
3. **Checkpoint inspection:** \`.checkpoints/<skill>.checkpoint.json\`
   files in the repo carry the structured event log per skill. The
   \`checkpoint:\` column in this trace tells you which file holds the
   detail for any specific event.
4. **PR diff:** \`#2208\` (the feature) and \`#2211\` (the fix) are the
   only code changes touching this surface in the window.

## What changed in v1.2

| Skill | v1.1 behaviour | v1.2 behaviour |
|---|---|---|
| app-architect | /discover asked everything from scratch | /discover --ticket pre-fills from PM context; /roadmap creates child tickets per sprint |
| git-ops | branch + commit + PR from prompt only | shaped from the linked ticket; transitions ticket on PR open / merge |
| code-auditor | findings recorded in checkpoint | also commented on the linked PM ticket |
| deploy-ops | per-environment deploy | also creates a deploy ticket linked to every commit's tickets; transitions per env |
| monitoring-ops | alert → PagerDuty | also opens an incident ticket linked to the most recent deploy ticket; auto-creates remediation sub-tickets when a postmortem lands |

The skill prose for each (in \`skills/<name>/SKILL.md\`) covers the
detection patterns, the failure modes, and the audit-pipeline
expectations for regulated environments.

Checkpoint: \`.checkpoints/integrations-engineer.checkpoint.json\` (v1.2 protocol).
`,
    },
  ],
  skills: ["app-architect", "git-ops", "deploy-ops", "monitoring-ops", "code-auditor", "integrations-engineer"],
  runtime: "≈ 12 exchanges",
  steps: [
    { type: "beat", label: "01 · Read the ticket", caption: "app-architect /discover pre-fills from Linear", skills: ["app-architect"] },

    {
      type: "exchange", role: "user",
      content: `/discover --ticket PLAT-4471`
    },
    {
      type: "exchange", role: "claude", skill: "app-architect",
      content:
`v1.2 PM-aware mode active. Reading the ticket through the configured Linear MCP.

\`\`\`
mcp.linear.get_issue("PLAT-4471") → 200 (3.4KB)
  title:       Add CSV export to /api/customers
  state:       Todo
  priority:    Medium (P3)
  cycle:       2026-W19
  assignee:    sam@onramp.dev
  labels:      [customer-success, exports]
  description: 2.1KB
  comments:    4 (ana×2, lily, sam)
  related:     PLAT-4472 (blocked-by), PLAT-4011 (precedent)
\`\`\`

Discovery shape — 8 standard questions; 5 pre-filled from the ticket:

- ✅ **Problem:** customer success copy-pastes the customer list into Sheets; that flow falls apart past ~50 rows. *(from ticket body)*
- ✅ **Users:** customer success ICs; acme-inc's compliance team is the immediate driver. *(from ticket body + ana's note)*
- ✅ **Surface:** new endpoint \`GET /api/customers.csv\` matching the existing JSON endpoint. *(from ticket body)*
- ✅ **Acceptance criteria:** RFC 4180, BOM (Karen at midmarket-corp), streaming (108k row tenant), auth + tenant match, specific filename. *(from ticket AC checklist)*
- ✅ **Out of scope:** the UI button (PLAT-4472), Excel \`.xlsx\` (PLAT-3201), per-column filtering (PLAT-3987). *(from ticket)*

Three questions remaining for you:

1. The ticket investigation notes point at \`src/api/audit-log.csv.ts\` (PLAT-4011) as the streaming template. **Confirm I should reuse that pattern**, or do you want a fresh approach?
2. CSV escaping — RFC 4180 strictly, or do we need Excel-specific quirks beyond the BOM (e.g. \`SEP=,\` injection, UTF-16 stub for the cohort that can't open UTF-8)?
3. Filename — the spec says \`customers-{tenant-slug}-{yyyy-mm-dd}.csv\`. Any time-zone preference for the date, or stick with UTC?`,
      artifacts: ["pm-config", "ticket-detail"],
    },
    {
      type: "exchange", role: "user",
      content: `1. Yes, reuse the audit-log streaming pattern. 2. RFC 4180 only; the one Excel user just needs the BOM. 3. UTC is fine.`
    },
    {
      type: "exchange", role: "claude", skill: "app-architect",
      content:
`Reading \`src/services/customers.ts\` to confirm the \`getCustomersForTenant\` signature before drafting:

\`\`\`ts
// src/services/customers.ts (current)
export async function getCustomersForTenant(opts: {
  tenantId: string;
  filters: CustomersFilter;
  cursor?: Cursor;
  limit?: number;
}): Promise<CustomersResult>;
\`\`\`

It already takes \`{tenantId, filters, cursor, limit}\`; it does **not**
expose a streaming variant — the function returns a fully-materialised
\`CustomersResult\`. I'll add an overload:

\`\`\`ts
export function getCustomersForTenant(opts: {
  tenantId: string;
  filters: CustomersFilter;
  stream: true;
}): AsyncIterable<CustomerRow>;
\`\`\`

JSON callers stay on the existing signature; the CSV endpoint gets the
async-iterable variant via the cursor under the hood. Mirrors what
\`audit-log.csv.ts\` does.

Spec produced (1 file: \`spec/plat-4471/00-overview.md\` — existing
project; only the new endpoint). Sprint plan: 1 sprint, 1 deliverable,
~3 hours of build time.

Writing back to Linear:

\`\`\`
mcp.linear.add_comment("PLAT-4471",
  body="<!-- opchain:app-architect:sprint-created:PLAT-4471/sprint-1 -->

        Sprint 1 — Add CSV export to /api/customers
        Deliverables:
          - GET /api/customers.csv handler (streaming)
          - csv RFC-4180 helper
          - getCustomersForTenant async-iterable overload
          - 7 tests covering happy + filter + auth + BOM + escape + heap regression
        Definition of done:
          - acceptance criteria all checked
          - code-auditor Grade A or better
          - bug-check PASS
          - staging smoke verified by ana + Karen
        Estimated effort: 3h")

mcp.linear.create_issue(
  parent="PLAT-4471",
  title="Sprint 1: CSV export endpoint",
  type="Chore",
  labels=["opchain", "agent-driven", "sprint"]
) → PLAT-4471/sprint-1
\`\`\`

Sprint plan approved? \`/build\` will start the Generator → Evaluator loop. Or \`/contract\` to negotiate the sprint-1 contract first.`,
    },

    { type: "beat", label: "02 · Build → benchmark → audit", caption: "Generator/Evaluator loop, then verify heap before /git-sync", skills: ["app-architect", "code-auditor"] },

    {
      type: "exchange", role: "user",
      content: `/build, then verify the heap claim before /git-sync.`
    },
    {
      type: "exchange", role: "claude", skill: "app-architect",
      content:
`\`/build\` — Generator → Evaluator loop:

\`\`\`
Generator (round 1)
  files written:
    src/api/customers.csv.ts                (handler, 64 LOC)
    src/lib/csv.ts                          (RFC 4180 helper, 78 LOC)
    src/services/customers.ts               (async-iterable overload, +14 LOC)
    tests/api/customers.csv.spec.ts         (7 tests, 194 LOC)
  build:                                     PASS
  unit tests:                                7 new + 147 existing = 154 PASS

Evaluator round 1
  Functionality:        9/10  — endpoint streams; BOM correct; filters work; auth enforced
  Feature Completeness: 9/10  — every AC checked + DoD step modeled
  Code Quality:         8/10  — solid; minor: csv.ts could be ~30 LOC shorter via generator
  Visual/UX:            n/a   — not a UI sprint
  → PASS
\`\`\`

Now the heap regression check. Running the integration test against
\`big-tenant\` (108k rows) with heap sampling enabled:

\`\`\`
$ vitest run tests/api/customers.csv.spec.ts -t "heap-bounded"
  ✓ stream-big-tenant-heap-bounded  (4.1s)
    heap p50: 31MB
    heap p95: 38MB
    heap peak: 41MB
    rows streamed: 108,442
    wall-clock: 3.2s
\`\`\`

**38MB p95 vs 622MB on the buffered JSON path. ~16× more memory-efficient.**
Wall-clock 3.2s (vs 4.1s buffered, despite emitting bytes 9× sooner).

Sprint passed in one round, heap regression confirmed. Handing off to git-ops.`,
    },
    {
      type: "exchange", role: "claude", skill: "git-ops",
      content:
`v1.2 PM-aware: the prompt \`/git-sync\` follows a recently-touched ticket, so I'll re-read it.

\`\`\`
mcp.linear.get_issue("PLAT-4471") → 200
  state:    Todo  → about to transition
\`\`\`

Pre-write check on the PR-opened comment marker:

\`\`\`
mcp.linear.list_comments("PLAT-4471") → marker
   <!-- opchain:git-ops:pr-opened:#2208 -->
   not present → safe to write
\`\`\`

Branch + commit + PR shaped from the ticket:

\`\`\`
branch:  feat/PLAT-4471-add-csv-export-customers
commit:  feat(api): add CSV export to /api/customers

         Adds GET /api/customers.csv returning RFC 4180 CSV...
         Refs: PLAT-4471

PR #2208 opened on github.com/onramp-inc/platform.
\`\`\`

Writing back to Linear:

\`\`\`
mcp.linear.add_comment("PLAT-4471",
  body="<!-- opchain:git-ops:pr-opened:#2208 -->
        PR opened: github.com/onramp-inc/platform/pull/2208
        Reviewers: yusuf (streaming pattern owner), priya (PLAT-4472 consumer)")
mcp.linear.save_issue("PLAT-4471", state="In Review")
\`\`\`

Auto-invoking **bug-check** before any merge action; running **code-auditor /audit pre-deploy** in parallel since the deploy gate will demand it.`,
      artifacts: ["linked-pr"],
    },
    {
      type: "exchange", role: "claude", skill: "code-auditor",
      content:
`code-auditor /audit pre-deploy on PR #2208.

\`\`\`
Files reviewed:        3 new (customers.csv.ts, csv.ts, customers.csv.spec.ts)
                       1 modified (services/customers.ts)
Findings:              0 blocking, 1 advisory
Advisory #1:           csv.ts could be ~30 LOC shorter using a Symbol.asyncIterator
                       generator; not blocking, leaving as a follow-up note.
Tests:                 7 new, 0 changed, 0 deleted (147 → 154 total)
Coverage:              new code 100% line, 100% branch
Type-check:            PASS
Lint:                  PASS
Secret-scan:           PASS
Grade:                 A
Wall-clock:            12.4s
\`\`\`

v1.2: posting back to Linear with a stable marker.

\`\`\`
mcp.linear.add_comment("PLAT-4471",
  body="<!-- opchain:code-auditor:audit-posted:#2208 -->
        Auditor: Grade A. 0 blocking, 1 advisory.
        Advisory: csv.ts is functional but could be ~30 LOC shorter via a
        Symbol.asyncIterator generator. Not a blocker; left for a future
        cleanup pass.")
\`\`\`

Bug-check returned PASS (1.4s). The PR is mergeable; deploy-ops can take over.`
    },

    { type: "beat", label: "03 · Deploy", caption: "deploy-ops creates the deploy ticket and threads through environments", skills: ["deploy-ops"] },

    {
      type: "exchange", role: "claude", skill: "deploy-ops",
      content:
`v1.2: \`/deploy staging\` walks the commit range, collects ticket refs, and creates the deploy ticket before doing anything else.

\`\`\`
range:           a8a254c..7ea6bf2  (2 commits)
linked tickets:  PLAT-4471
audit gate:      PASS (cached from /git-sync, age 4m)
bug-check:       PASS

Pre-create check:
  mcp.linear.list_issues(query="<!-- opchain:deploy-ops:deploy-created:7ea6bf2 -->")
  → no match → safe to create

mcp.linear.create_issue(
  type="Deploy",
  title="Deploy 2026-05-04 14:02 — staging → prod (1 ticket)",
  description="<!-- opchain:deploy-ops:deploy-created:7ea6bf2 --> ...",
  parent_relations=["PLAT-4471"],
  labels=["opchain", "agent-driven", "deploy", "environment:prod"]
) → PLAT-4485

→ wrangler deploy --env staging
✓ deployed in 37s
✓ smoke tests passed (5/5)

mcp.linear.add_comment("PLAT-4485",
  body="<!-- opchain:deploy-ops:staging-verified:PLAT-4485 -->
        Smoke tests passed against staging.api.onramp.dev. Audit gate clean. Awaiting human approval for prod.")
mcp.linear.save_issue("PLAT-4485", state="Staging verified")
\`\`\`

Prod gate is open when you're ready. Smoke results in the deploy-ticket artifact.`,
    },
    {
      type: "exchange", role: "user",
      content: `Pinged ana, Karen verified BOM works on her Windows box. Approve. /deploy prod.`
    },
    {
      type: "exchange", role: "claude", skill: "deploy-ops",
      content:
`\`\`\`
→ wrangler deploy
✓ deployed in 42s
✓ smoke tests passed (5/5)
✓ prod headers: X-Opchain-Version: 7ea6bf2

mcp.linear.add_comment("PLAT-4485",
  body="<!-- opchain:deploy-ops:prod-shipped:PLAT-4485 -->
        Prod deployed: 7ea6bf2. Smoke tests pass.")
mcp.linear.save_issue("PLAT-4485", state="Shipped")

mcp.linear.add_comment("PLAT-4471",
  body="<!-- opchain:deploy-ops:linked-shipped:PLAT-4485:PLAT-4471 -->
        Shipped to prod via deploy PLAT-4485.")
mcp.linear.save_issue("PLAT-4471", state="Done")
\`\`\`

\`PLAT-4471\` is closed; \`PLAT-4485\` is the deploy record. Deploy time start-to-prod was 8 min, including the human approval pause.

Asking **monitoring-ops** to attach a 30-min post-deploy sentinel against \`api.onramp.dev\`.`,
      artifacts: ["deploy-ticket"],
    },
    {
      type: "exchange", role: "claude", skill: "monitoring-ops",
      content:
`/watch api.onramp.dev — 30-min sentinel armed against the \`api/customers\` dashboard.

\`\`\`
[14:11Z]  sentinel armed: 30 min window
[14:42Z]  sentinel complete — 0 alerts fired, p99 latency steady ~120ms across
          both JSON and CSV variants; heap p95 stayed in budget; no Sentry events
\`\`\`

\`\`\`
mcp.linear.add_comment("PLAT-4485",
  body="<!-- opchain:monitoring-ops:sentinel-complete:PLAT-4485 -->
        30-min post-deploy sentinel complete. No anomalies on
        api/customers dashboard. p99 latency steady ~120ms across both JSON
        and CSV variants. No customers_csv_p95_latency_high fires.")
\`\`\`

Sentinel clean. PLAT-4485 stays Shipped.`,
    },

    { type: "beat", label: "04 · Incident the next morning", caption: "monitoring-ops opens an incident ticket linked to the deploy", skills: ["monitoring-ops"] },

    {
      type: "exchange", role: "claude", skill: "monitoring-ops",
      content:
`v1.2: alert \`customers_csv_p95_latency_high\` (SEV-3) fired at 09:14:33 UTC. Looking up the runbook + most recent deploy.

\`\`\`
recent deploys (last 24h): PLAT-4485 (introduced /api/customers.csv, 18h ago) ← likely culprit
on-call: sam@onramp.dev
runbook: docs/runbooks/api-latency-investigation
escalation: PagerDuty EP-PLAT-BACKEND (from pm.yaml pagerduty_routing)

Pre-create check:
  mcp.linear.list_issues(query="<!-- opchain:monitoring-ops:incident-fired:PD-INC-018347 -->")
  → no match → safe to create

mcp.linear.create_issue(
  type="Incident",
  title="Incident: customers.csv p95 latency · 2026-05-05 09:14 UTC",
  description="<!-- opchain:monitoring-ops:incident-fired:PD-INC-018347 -->
               <<full alert payload + symptoms + dashboards described + likely-culprit>>",
  parent_relations=["PLAT-4485"],
  labels=["opchain", "agent-driven", "incident", "service:api/customers.csv", "severity:SEV-3", "postmortem-required"]
) → PLAT-4503

→ pagerduty page sam
\`\`\`

The on-call and the relevant deploy are both linked. Paging sam now.`,
    },
    {
      type: "exchange", role: "claude", skill: "monitoring-ops",
      content:
`Alert auto-resolved at 09:30:14 (16 min impact). sam shipped the cursor-batch fix; published the postmortem at 11:48; four remediation sub-tickets auto-filed.

\`\`\`
mcp.linear.add_comment("PLAT-4503",
  body="<!-- opchain:monitoring-ops:auto-resolved:PLAT-4503 -->
        Alert auto-resolved (16 min). Transitioning to Resolved (PM pending).")
mcp.linear.save_issue("PLAT-4503", state="Resolved (PM pending)")

mcp.linear.create_issue x4 (sub-tickets, parent=PLAT-4503):
  PLAT-4504  Fix Postgres cursor BATCH_SIZE read                (sam, done same-hour)
  PLAT-4505  Add p95 800ms warn alert tier                      (vee)
  PLAT-4506  Add big-tenant CSV load test to CI on every PR     (yusuf)
  PLAT-4507  Document cursor.read() default in style guide      (priya)

mcp.linear.add_comment("PLAT-4503",
  body="<!-- opchain:monitoring-ops:postmortem:PLAT-4503 -->
        Postmortem published: docs.onramp.dev/postmortems/2026-05-05-customers-csv-latency
        4 remediation sub-tickets filed.")
mcp.linear.save_issue("PLAT-4503", state="Done")
\`\`\`

The whole thread — feature ticket, sprint child, PR, deploy ticket, incident ticket, four remediation sub-tickets — lives in Linear under \`PLAT-4471\`. Anyone searching for it two weeks later sees the full audit trail without leaving the PM tool. The grep-able markers per skill are documented in the timeline artifact.`,
      artifacts: ["incident-ticket", "end-to-end-trace"],
    },
  ],
};
