import type { Walkthrough } from "./types";

/**
 * Scenario 10 (v1.3 hero) — "OnRamp" picks up Linear ticket PLAT-5102 at
 * 09:14 (alert fired earlier; on-call filed the bug) and rides the v1.3
 * runtime-PM loop end-to-end on a single Linear thread: ticket → branch →
 * PR → staging → prod → incident → postmortem. v1.2 taught the prose;
 * v1.3 makes every MCP call real with retry/backoff/idempotency markers
 * and a deferred-action queue. The Linear thread becomes the
 * audit-ready record of the engineering work — comments on PLAT-5102
 * are produced by oc-app-architect, oc-git-ops, oc-deploy-ops, oc-monitoring-ops,
 * each with its own idempotency marker so retries / resumed sessions
 * never double-post.
 */
export const runtimePmLoop: Walkthrough = {
  id: "runtime-pm-loop",
  title: "Ticket → ship → incident → postmortem on one Linear thread",
  tagline: "v1.3 hero · runtime PM-MCP loop",
  summary:
    "v1.3 hero scenario: a real Linear ticket (PLAT-5102) rides the full pipeline. Every MCP call carries an idempotency marker; retries short-circuit; a transient 503 mid-deploy lands a deferred action that flushes cleanly. Six skills, one thread, audit-ready.",
  description:
    "OnRamp's customer-list endpoint started timing out at 09:11. PagerDuty paged Maya at 09:13; she filed PLAT-5102 at 09:14 with the alert payload pasted in. By 11:02 the fix is live in prod, the incident ticket is resolved, and the postmortem is published — every step recorded as comments on the Linear thread by the appropriate skill, with idempotency markers so the agent can crash-restart any time without polluting the ticket history. v1.3 swapped v1.2's `mcp.<provider>.<verb>` placeholders for concrete tool names like `mcp__claude_ai_Linear__save_comment` and added a deferred-action queue: when Linear returned a 503 during /oc-deploy prod, the comment was queued in `oc-deploy-ops.checkpoint.json` and flushed two minutes later when Linear came back. The artifact set is the complete Linear timeline (parent ticket + deploy ticket + incident ticket + remediation sub-tickets) plus the four checkpoint files showing how state crossed the skill boundaries.",
  inputs: [
    "Series B SaaS · OnRamp Inc · ~30 engineers · Linear (team PLAT) as system-of-record",
    "On-call engineer Maya files PLAT-5102 from a PagerDuty alert at 09:14",
    "v1.3 opchain installed · all 18 skills at 1.3.0 · `.opchain/pm.yaml` configured for Linear",
    "Linear MCP server reachable through Claude Code's `mcp.json`",
  ],
  outputs: [
    {
      id: "pm-yaml",
      label: "`.opchain/pm.yaml` — Linear config with v1.3 tool_overrides",
      kind: "config.yaml",
      body:
`# .opchain/pm.yaml — OnRamp v1.3 (provider: linear)
# Generated by oc-app-architect /init; reviewed quarterly.
# v1.3 protocol reference: skills/oc-integrations-engineer/references/pm-mcp-protocol.md

provider: linear
team_or_project: PLAT
mcp_server: linear

issue_types:
  feature:  Feature
  bug:      Bug
  chore:    Chore
  deploy:   Deploy
  incident: Incident
  release:  Release

states:
  in_progress: "In Progress"
  in_review:   "In Review"
  done:        "Done"
  extended:
    blocked:                       "Blocked"
    staging-verified:              "Staging verified"
    shipped:                       "Shipped"
    rolled-back:                   "Rolled back"
    resolved-pending-postmortem:   "Resolved (PM pending)"

labels_default: [opchain, agent-driven]

remediation_owners:
  backend:  maya@onramp.dev
  frontend: priya@onramp.dev
  data:     yusuf@onramp.dev
  infra:    vee@onramp.dev

# v1.3 behaviour
create_child_tickets: true
cycle_aware: true
comment_dedupe_window: 7d
pr_template: ".github/pull_request_template.md"

# Required-audit transitions: oc-deploy-ops will not transition into these
# states without a passing audit gate; the gate result is cached per-SHA
# so the same gate doesn't run twice within a pipeline.
audit_required_for_state_transitions:
  - "Staging verified"
  - "Shipped"

pagerduty_routing:
  api/customers:        EP-PLAT-BACKEND
  api/customers.csv:    EP-PLAT-BACKEND
  worker/webhooks:      EP-PLAT-INFRA

worktree_naming: "fix/{ticket-id}-{slug}"

# v1.3 addition: idempotency marker template.
# Every agent-written comment carries one of these so retries are no-ops.
idempotency_marker_template: "<!-- opchain:{skill}:{event}:{id} -->"

# v1.3 addition: where deferred-action queue entries live (per-skill checkpoint).
# protocol §4 — see references/pm-mcp-protocol.md "Deferred actions"
deferred_actions_storage: ".checkpoints/{skill}.checkpoint.json#pm_deferred_actions"

# v1.3 addition: tool_overrides for brokered MCP environments (HIPAA / FedRAMP).
# OnRamp is not regulated, so the registry defaults win; this block is empty.
# Example for a corp-broker environment (commented):
#
#   tool_overrides:
#     get_issue:        mcp__corp-linear-broker__get_issue
#     list_issues:      mcp__corp-linear-broker__list_issues
#     list_comments:    mcp__corp-linear-broker__list_comments
#     save_comment:     mcp__corp-linear-broker__save_comment
#     save_issue:       mcp__corp-linear-broker__save_issue
#     audit_emit_to:    mcp__corp-audit-broker__emit_event
#
tool_overrides: {}
`,
    },
    {
      id: "plat-5102",
      label: "PLAT-5102 — the source bug ticket (filed by on-call)",
      kind: "linear.md",
      body:
`# PLAT-5102 — API latency spike on customer-list pagination

<!-- opchain:oc-release-ops:sprint-child:v1.3.0:source-bug -->

**URL:** https://linear.app/onramp/issue/PLAT-5102
**Project:** Platform · **Cycle:** 2026-W19 · **Type:** Bug · **State:** Todo → In Progress (transition by oc-git-ops at 09:31) → In Review → Done
**Priority:** High (P2) — SEV-3 oncall escalation · **Estimate:** 1 · **Reporter:** maya@onramp.dev (on-call) · **Assignee:** maya@onramp.dev
**Watchers:** maya@onramp.dev, ops-rotation@onramp.dev, vee@onramp.dev (infra), yusuf@onramp.dev (data)
**Labels:** \`bug\`, \`opchain\`, \`agent-driven\`, \`service:api/customers\`, \`from-pagerduty\`, \`priority-incident-linked\`
**PagerDuty incident:** PD-INC-018401 (acked at 09:13:11Z)
**Created:** 2026-05-08T09:14:22Z

## Description

PagerDuty alert \`api-latency-customers-p99\` fired at **09:11:47Z** during
the 09:00-10:00Z traffic ramp. P99 latency on
\`GET /api/customers?cursor=...\` jumped from ~120ms baseline to ~3.4s.
Error rate stayed at 0.0% across the window — this is a **slowdown, not
a 5xx burst.** Customer Success (lily@) reports the admin UI feels
sluggish too — that's the same query path.

The customer-list endpoint paginates by created-at cursor. Suspicion is
the composite index on \`(team_id, created_at)\` got dropped or
deactivated during the 2026-05-07 03:05Z migration cleanup, or that the
query planner flipped under load. The most recent prod ship before the
spike is **c4f8a21 at 08:42Z (release v6.18.4 backend) — touches
unrelated paths, but it warrants a glance.**

**Runbook:** https://runbooks.onramp.dev/api-latency-investigation
**Dashboard:** https://oc-app.datadoghq.com/dashboard/onramp-api-customers

## Alert payload (verbatim from PagerDuty)

\`\`\`json
{
  "incident_id": "PD-INC-018401",
  "incident_key": "api-latency-customers-p99:api/customers",
  "service": { "id": "PS-PLAT-BACKEND", "name": "api/customers" },
  "urgency": "high",
  "severity": "warning",
  "status": "triggered",
  "created_at": "2026-05-08T09:13:08Z",
  "description": "api-latency-customers-p99 triggered on api/customers",
  "details": {
    "metric": "request_duration_p99",
    "endpoint": "/api/customers",
    "p99_observed_ms": 3412,
    "p99_threshold_ms": 800,
    "p95_observed_ms": 1910,
    "p95_threshold_ms": 500,
    "p50_observed_ms": 71,
    "window_seconds": 300,
    "request_count_in_window": 184,
    "error_rate": 0.0,
    "tenant_breakdown": {
      "acme-inc":     { "requests": 92, "p99_ms": 4880 },
      "midmarket-corp": { "requests": 41, "p99_ms": 2120 },
      "other_aggregated": { "requests": 51, "p99_ms": 980 }
    }
  },
  "links": [
    { "name": "Dashboard", "href": "https://oc-app.datadoghq.com/dashboard/onramp-api-customers" },
    { "name": "Runbook", "href": "https://runbooks.onramp.dev/api-latency-investigation" }
  ]
}
\`\`\`

## Dashboards (described)

### \`api/customers\` p99 latency (last 60 min)

The graph shows p99 holding at ~120ms steady-state from 08:00-09:11Z,
then **a sharp step-up at 09:11:18Z to ~3.4s** that plateaus through
the 09:14 alert fire. \`/api/health\` and the rest of \`/api/*\` are
unaffected, so the regression is endpoint-local. acme-inc's slice
(largest tenant by row count) sees ~50% worse latency than the
aggregated other-tenant slice — strong hint that the regression
scales with row count.

### Request volume (last 60 min)

Volume on \`/api/customers\` jumped from ~3 req/min overnight to
~37 req/min at 09:11Z — the typical Monday-morning ramp as CS users
log in. Not the cause; just the workload that exposes whatever
regressed.

### Postgres query timings (Datadog APM)

The \`SELECT FROM customers WHERE team_id=$1 AND created_at > $2 ORDER BY created_at LIMIT $3\`
query trace shows the same SQL string at 09:00Z executing in 8ms p99
and at 09:11Z executing in 2.4s p99. **The SQL didn't change; the
query plan did.** Almost certainly an index issue.

## Symptoms

- **p50** stable at ~70ms (no fixed alert; baseline OK — points away from a hot-path slowdown that hits every request)
- **p95** climbed from 180ms to **1.9s** (+955%)
- **p99** climbed from 300ms to **3.4s** (+1033%)
- **request rate** +20% over Monday baseline (typical ramp)
- **error rate** 0.0% (no 5xx, no timeouts in the 5min window; slow but completing)
- **per-tenant slope** correlates with row count (acme @ 108k rows is the worst)
- **downstream** customer-csv endpoint also slow (same query path)
- **no recent deploys** to this surface in the last 4 hours

## Reproduction

\`\`\`
$ curl -sS -w '\\n%{time_total}\\n' \\
    -H 'Authorization: Bearer ...' \\
    'https://oc-api.onramp.dev/api/customers?cursor=eyJjcmVhdGVkX2F0Ijoi...&limit=200'
[... 200 rows JSON ...]
3.18

$ curl -sS -w '\\n%{time_total}\\n' \\
    -H 'Authorization: Bearer ...' \\
    'https://staging.api.onramp.dev/api/customers?cursor=eyJjcmVhdGVkX2F0Ijoi...&limit=200'
[... 200 rows JSON ...]
0.07
\`\`\`

Staging (which still has the index) returns in 70ms; prod returns in 3.18s
on the same query against the same tenant data shape. **Confirms a
prod-specific regression.**

## EXPLAIN ANALYZE (snapshot from prod at 09:13Z)

\`\`\`
QUERY PLAN
─────────────────────────────────────────────────────────────────────────
 Limit  (cost=0.43..2410.18 rows=200 width=412) (actual time=2178.4..2391.2 rows=200 loops=1)
   ->  Sort  (cost=0.43..27412.18 rows=11200 width=412) (actual time=2178.4..2384.1 rows=200 loops=1)
         Sort Key: created_at DESC
         Sort Method: external merge  Disk: 28200kB
         ->  Seq Scan on customers  (cost=0.00..24010.18 rows=11200 width=412)
                                    (actual time=12.8..1841.6 rows=108442 loops=1)
               Filter: ((team_id = $1) AND (created_at > $2))
               Rows Removed by Filter: 0
 Planning Time: 0.382 ms
 Execution Time: 2398.214 ms
─────────────────────────────────────────────────────────────────────────
\`\`\`

**Seq Scan on customers.** That's the smoking gun — the planner is
scanning the full \`customers\` table and sorting on disk, instead of
walking the composite index. The expected plan (still observable on
staging):

\`\`\`
 Limit  (cost=0.43..23.14 rows=200 width=412) (actual time=0.024..1.823 rows=200 loops=1)
   ->  Index Scan Backward using idx_customers_team_id_created_at on customers
         Index Cond: ((team_id = $1) AND (created_at > $2))
\`\`\`

## Investigation (Maya, before filing — 09:13)

In the 90 seconds between page and filing:

1. Confirmed staging is unaffected (above).
2. Checked recent deploys via \`/api/health\`: prod SHA c4f8a21 (release v6.18.4) shipped 08:42Z — touched \`worker/billing\` paths, **not** \`api/customers\`. Unlikely culprit on a per-line review.
3. Pulled the \`migrations/\` directory log:

\`\`\`
$ git log --oneline -10 -- migrations/
a221f08  2026-05-07 03:05  data: drop dupe indexes (cleanup)
8f3c7d2  2026-05-04 14:10  feat: customer.csv streaming
...
\`\`\`

The 03:05Z "drop dupe indexes" commit (data team) lands ~30 hours
before the symptoms. Either the drop migrated on prod without anyone
noticing the symptom (low traffic overnight + auto-vacuum keeping the
seq scan fast enough until the Monday ramp), or the planner flipped
this morning for a different reason.

**Strong hypothesis:** the migration dropped \`idx_customers_team_id_created_at\`
thinking it was a duplicate of \`idx_customers_team_id\`. It's not — the
composite is what supports the cursor's compound predicate. We need it
back.

## Recent deploys (last 24h)

\`\`\`
2026-05-07T03:05Z  a221f08  data: drop dupe indexes (cleanup)            ← strong suspect
2026-05-07T08:42Z  c4f8a21  release v6.18.4 backend                       (unrelated paths)
\`\`\`

## Hypothesis ranking

| # | Hypothesis | Likelihood | Evidence |
|---|---|---|---|
| 1 | \`idx_customers_team_id_created_at\` dropped in 2026-05-07 03:05Z migration | HIGH | EXPLAIN shows Seq Scan; staging still has the index; the migration explicitly dropped "duplicate" indexes |
| 2 | Postgres autovacuum / stats drift causing planner to choose Seq Scan | MED | Possible but doesn't explain the staging/prod asymmetry |
| 3 | A row-count threshold flipped today (just crossed N where Seq Scan loses) | LOW | Doesn't explain the discontinuous jump; row-count changes are gradual |
| 4 | Worker memory pressure causing forced replan | LOW | No worker memory anomalies in the dashboards |

## Definition of done

- [ ] Restore the composite index (forward-only migration; \`CREATE INDEX CONCURRENTLY\` to avoid blocking writes)
- [ ] Verify prod query plan reverts to Index Scan
- [ ] Regression test: a pytest assertion that the planner chooses the index for this query on the seeded dataset (\`pg_explain\` parsing in CI)
- [ ] Alert tuned to fire on a single-tenant p99 > 800ms (rather than aggregate); catches the next regression sooner
- [ ] Postmortem published within 2h of resolution
- [ ] Remediation sub-tickets filed

## Acceptance

- p99 back under 500ms on the customer-list endpoint within 30 min of fix deploy
- query plan stable at >5× current load (verified with k6 against staging post-fix)
- regression test in place (PR will fail CI if the plan reverts)

## Activity log

\`\`\`
2026-05-08 09:11:18  monitoring     latency p99 first elevation observed
2026-05-08 09:13:08  pagerduty      alert fired
2026-05-08 09:13:11  maya@          PagerDuty ack
2026-05-08 09:14:22  maya@          PLAT-5102 created (Todo, P2, est 1)
2026-05-08 09:14:23  maya@          labeled "bug", "service:api/customers", "from-pagerduty"
2026-05-08 09:14:24  maya@          added to cycle 2026-W19
2026-05-08 09:14:25  maya@          self-assigned
2026-05-08 09:31:46  oc-git-ops        state transitioned: Todo → In Progress
\`\`\`

Checkpoint reference: \`.checkpoints/oc-monitoring-ops.checkpoint.json\` →
\`incidents.PLAT-5102.source\`.
`,
    },
    {
      id: "deploy-ticket",
      label: "PLAT-5103 — auto-created deploy ticket (oc-deploy-ops)",
      kind: "linear.md",
      body:
`# PLAT-5103 — Deploy: prod c4f8a21..ea71b9c

<!-- opchain:oc-deploy-ops:deploy-created:prod:ea71b9c -->

**URL:** https://linear.app/onramp/issue/PLAT-5103
**Project:** Platform · **Type:** Deploy · **State:** Staging verified → Shipped
**Priority:** High (auto-elevated because of parent priority) · **Reporter:** opchain-deploy-ops (bot) · **Assignee:** maya@onramp.dev
**Parent:** [PLAT-5102](https://linear.app/onramp/issue/PLAT-5102)
**Labels:** \`opchain\`, \`agent-driven\`, \`deploy\`, \`environment:prod\`, \`hotfix\`
**Watchers:** maya@onramp.dev, ops-rotation@onramp.dev, lily@onramp.dev
**Created:** 2026-05-08T10:08:14Z · **Closed:** 2026-05-08T10:42:11Z

## Description

Auto-created when \`/oc-deploy staging\` started after the audit gate passed.
oc-deploy-ops walked the commit range (1 commit) and extracted the
\`Refs: PLAT-5102\` trailer from \`ea71b9c\`.

\`\`\`
Environment:     prod (via staging)
Commit range:    c4f8a21..ea71b9c  (1 commit)
Linked tickets:  PLAT-5102 (1)
Audit gate:      PASS (grade A-)
Bug-check:       PASS
Migrations:      1 (forward-only; CREATE INDEX CONCURRENTLY)
Env / config:    0 changes
Dependencies:    0 added, 0 removed, 0 updated
Risk band:       LOW-MED (concurrent index build; observable lock window but non-blocking)
\`\`\`

## Commit range

| SHA | Subject | Author | Ticket refs |
|---|---|---|---|
| \`ea71b9c\` | fix(api): restore (team_id, created_at) composite index for paginate | maya@ | PLAT-5102 |

## Migrations applied

\`\`\`sql
-- migrations/20260508_restore_paginate_index.sql
CREATE INDEX CONCURRENTLY IF NOT EXISTS
  idx_customers_team_id_created_at
  ON customers (team_id, created_at DESC);
\`\`\`

**Risk note:** \`CONCURRENTLY\` avoids the AccessExclusiveLock that a
plain \`CREATE INDEX\` would take. Lock window observable in
\`pg_stat_activity\` but **does not block writes**. Estimated build time
on prod's \`customers\` table size: ~45-90s.

## Env / config changes

None.

## Dependencies

\`\`\`
npm diff c4f8a21..ea71b9c -- package-lock.json
(no changes)
\`\`\`

## Audit gate output (verbatim)

\`\`\`
[oc-code-auditor /oc-audit pre-deploy]
  Files reviewed:    2 (migrations/20260508_restore_paginate_index.sql,
                        tests/regression/test_customer_list_plan.py)
  Findings:          1 advisory ("consider adding the index to a docstring
                                  in services/customers.ts for future readers")
  Tests:             1 new regression test, 153 existing, 0 failing
  Coverage:          new code 100% (the migration is a single statement)
  Type-check:        PASS
  Lint:              PASS
  Grade:             A-
  Wall-clock:        9.2s
  Note:              advisory only; not blocking

[oc-security-auditor /oc-sec verify]
  Threat-model scope: migrations
  STRIDE findings:    0 new
  CREATE INDEX CONCURRENTLY: safe (no schema mutation; no row-level lock)
  Verdict:            PASS

[oc-bug-check pre-commit]
  Type / Lint / Build / Dep-audit / Secret-scan: all PASS (1.1s)
\`\`\`

## Smoke tests (staging)

\`\`\`
$ curl -fsS https://staging.api.onramp.dev/api/health | jq '.version'
"ea71b9c"
  → PASS

$ time curl -fsS -H 'Authorization: Bearer ...' \\
    'https://staging.api.onramp.dev/api/customers?cursor=...&limit=200' \\
    | jq '. | length'
200
real    0m0.078s
  → PASS  (78ms p99 vs the 3.4s prod baseline pre-fix)

$ curl -fsS -H 'Authorization: Bearer ...' \\
    'https://staging.api.onramp.dev/api/customers.csv?limit=200' | head -c 3 | xxd
00000000: efbb bf                                  ...
  → PASS  (downstream csv endpoint also healthy)

$ k6 run --vus 50 --duration 60s scripts/k6-customer-list.js
  ✓ p95 < 250ms (observed: 142ms)
  ✓ p99 < 500ms (observed: 198ms)
  → PASS  (5× current prod load held under threshold)

All 4 smoke checks PASS.
\`\`\`

## Watch list (post-deploy)

| Dashboard / Alert | URL | Why |
|---|---|---|
| \`api/customers\` p99 latency | https://oc-app.datadoghq.com/dashboard/onramp-api-customers | The regression dashboard; this is what should drop to baseline |
| Postgres index-build status | https://oc-app.datadoghq.com/.../postgres-locks | \`CREATE INDEX CONCURRENTLY\` build progress; expected to clear in 90s |
| \`api-latency-customers-p99\` alert | (existing) | Should auto-resolve once latency clears the threshold |
| Worker memory | https://dash.cloudflare.com/.../worker-analytics | Sanity check (none expected) |
| Sentry — \`PLAT-5102\` tag | https://sentry.io/onramp/issues/?query=tag:PLAT-5102 | Any related exceptions |

## Rollback plan

If post-deploy regression observed within 30 minutes:

\`\`\`bash
# 1. Drop the index (the only thing we added; safe — won't break the JSON contract).
psql $DATABASE_URL -c "DROP INDEX CONCURRENTLY IF EXISTS idx_customers_team_id_created_at;"
# 2. Revert the worker deploy (returns to c4f8a21 — the slow state).
npx wrangler deployments list | head -3
npx wrangler rollback <prior-id>
\`\`\`

**Important:** rolling back the worker without dropping the index is
fine — the index helps regardless of which worker version is running.
Rolling back the index alone returns us to the slow state, which is
worse than current. **If in doubt, leave the index, revert the worker.**

## Comments

### 10:08:14Z · opchain-deploy-ops · staging deploy starting

\`\`\`
Auto-created. Audit gate clean (grade A-). 1 commit; 1 linked ticket.
1 migration (concurrent index build). Beginning staging deploy.
\`\`\`

### 10:14Z · opchain-deploy-ops · staging-verified

\`\`\`
<!-- opchain:oc-deploy-ops:staging-verified:PLAT-5103 -->

Smoke tests PASS (4/4):
  - GET /api/customers?cursor=... · p99=78ms (was 3.4s on prod baseline)
  - GET /api/health · 200 / SHA ea71b9c
  - GET /api/customers.csv · 200 / BOM intact
  - k6 5× load test · p99=198ms

Transitioned: Staging verified.
URL: https://staging.api.onramp.dev
\`\`\`

### 10:38Z · maya@ · approving prod

\`\`\`
Plan looks right; index built clean on staging in 41s. Going ahead.
\`\`\`

### 10:42Z · opchain-deploy-ops · prod-shipped (DEFERRED, then flushed)

\`\`\`
<!-- opchain:oc-deploy-ops:prod-shipped:PLAT-5103 -->

PROD SHIP · ea71b9c · v6.18.5
URL: https://oc-api.onramp.dev
Version stamp confirmed via /api/health: ea71b9c
Index built in 67s; query plan flipped to Index Scan immediately;
p99 latency dropped from 3.4s to ~110ms within 15s.

[Initially deferred 10:38Z — Linear returned 503 on save_comment.
 retriable=true, attempts=3 exhausted in 15s budget.
 Flushed at 10:42Z when Linear recovered. See
 oc-deploy-ops.checkpoint.json pm_flush_log[] for the audit trace.]
\`\`\`

### 10:42Z · opchain-deploy-ops · linked-shipped (PLAT-5102)

\`\`\`
<!-- opchain:oc-deploy-ops:linked-shipped:PLAT-5103:PLAT-5102 -->

Shipped to prod via deploy PLAT-5103 (release v6.18.5).
PLAT-5102's fix is live. Transitioning parent to Done.
\`\`\`

### 10:42:30Z · maya@

\`\`\`
Confirmed on dashboards. p99 back to ~110ms across all tenants.
acme-inc slice down from 4.9s to 130ms.
\`\`\`

## Activity log

\`\`\`
2026-05-08 10:08:14  oc-deploy-ops     created (staging deploy starting)
2026-05-08 10:08:48  oc-deploy-ops     staging build complete (34s)
2026-05-08 10:09:14  oc-deploy-ops     migration applied (concurrent index build 41s)
2026-05-08 10:14:02  oc-deploy-ops     state transitioned: → Staging verified
2026-05-08 10:38:08  oc-deploy-ops     prod deploy invoked
2026-05-08 10:38:14  oc-deploy-ops     prod-shipped comment DEFERRED (Linear 503)
2026-05-08 10:42:03  oc-deploy-ops     /oc-deploy --retry-pm flushed 1 action
2026-05-08 10:42:08  oc-deploy-ops     linked-shipped comment posted on PLAT-5102
2026-05-08 10:42:11  oc-deploy-ops     state transitioned: → Shipped
\`\`\`

## Linked

- parent: [PLAT-5102 — API latency spike on customer-list pagination](https://linear.app/onramp/issue/PLAT-5102)
- pull-request: https://github.com/onramp-inc/platform/pull/2243
- monitoring-sentinel: \`.checkpoints/oc-monitoring-ops.checkpoint.json#sentinels.PLAT-5103\` (30-min armed)

Checkpoint: \`.checkpoints/oc-deploy-ops.checkpoint.json\` → \`deploys.PLAT-5103\`.
`,
    },
    {
      id: "incident-ticket",
      label: "PLAT-5104 — incident ticket (oc-monitoring-ops, unrelated)",
      kind: "linear.md",
      body:
`# PLAT-5104 — Incident: webhook-replay queue depth alert

<!-- opchain:oc-monitoring-ops:incident-fired:evt-2026-05-08-101201 -->

**URL:** https://linear.app/onramp/issue/PLAT-5104
**Project:** Platform · **Type:** Incident · **Severity:** SEV-3 · **State:** In Progress → Resolved (PM pending) → Done
**Priority:** High (auto) · **Reporter:** opchain-monitoring-ops (bot) · **Assignee:** maya@onramp.dev (on-call)
**Parent:** [PLAT-5103](https://linear.app/onramp/issue/PLAT-5103) (most recent open deploy — likely-culprit link, ultimately unrelated)
**Labels:** \`opchain\`, \`agent-driven\`, \`incident\`, \`service:worker/webhooks\`, \`severity:SEV-3\`, \`upstream-caused\`, \`postmortem-required\`
**Watchers:** maya@onramp.dev, vee@onramp.dev (infra), ops-rotation@onramp.dev
**Created:** 2026-05-08T10:12:01Z · **Resolved:** 2026-05-08T10:31:29Z (19m 28s) · **Closed:** 2026-05-08T11:18:14Z

## Description

Auto-opened when \`webhook-replay-queue-depth\` PagerDuty alert fired at
10:12:01Z, ~30 minutes after the PLAT-5103 prod ship. oc-monitoring-ops
correlated to PLAT-5103 as the parent because the deploy ticket is
still open and the alert fired within the post-deploy window.

**Initial assessment** (in the description body when created): PLAT-5103
(customer-list paginate fix) does not touch the webhook-worker. The
correlation is **temporal coincidence**, not causal. Confirmed during
investigation.

## Alert payload (verbatim from PagerDuty)

\`\`\`json
{
  "incident_id": "PD-INC-018412",
  "incident_key": "webhook-replay-queue-depth:worker/webhooks",
  "service": { "id": "PS-PLAT-INFRA", "name": "worker/webhooks" },
  "urgency": "high",
  "severity": "warning",
  "status": "triggered",
  "created_at": "2026-05-08T10:12:01Z",
  "description": "webhook-replay-queue-depth fired",
  "details": {
    "metric": "queue_depth",
    "queue_name": "webhook-replay",
    "depth_observed": 4127,
    "depth_threshold": 2000,
    "oldest_item_age_s": 47,
    "publish_rate_per_s": 32,
    "drain_rate_per_s": 0.8,
    "upstream_endpoint": "api.partner-x.com"
  }
}
\`\`\`

## Dashboards (described)

### Webhook replay queue depth (last 60 min)

Graph shows queue depth at ~10-30 messages steady-state from 09:00-10:11Z,
then a **sharp climb starting 10:11:38Z** reaching 4,127 by alert fire
at 10:12:01Z, plateauing around 4,600 through ~10:25Z, then draining
back to ~50 by 10:31Z. Publish rate is steady (~32/s — normal); the
drain rate collapsed to ~0.8/s.

### Upstream partner-x.com latency

A separate Datadog synthetic shows api.partner-x.com returning 503s
at 10:11:30-10:30:48Z — **a 19-minute upstream outage at the receiver
side, not our problem.** Their status page confirmed at 10:35Z.

## Per-event comments

### 10:12:01Z · opchain-monitoring-ops · auto-correlated

\`\`\`
<!-- opchain:oc-monitoring-ops:incident-fired:evt-2026-05-08-101201 -->

Alert fired. Initial correlation:
  - Parent set to PLAT-5103 (most recent open deploy, 30 min ago).
  - Note: PLAT-5103 (customer-list paginate fix) does NOT touch
    webhook-worker. Correlation is likely temporal not causal.
  - Paging on-call: maya@onramp.dev (rotation: ops-rotation).
  - Runbook: https://runbooks.onramp.dev/webhook-replay
\`\`\`

### 10:13Z · maya@ (PagerDuty ack)

\`\`\`
<!-- opchain:oc-monitoring-ops:acked:PLAT-5104:maya -->

Acked. Pulling up dashboards. Will rule out PLAT-5103 quickly.
\`\`\`

### 10:18Z · opchain-monitoring-ops · burst dedupe

\`\`\`
<!-- opchain:oc-monitoring-ops:burst-event:PLAT-5104:event-2 -->

Second alert fire at 10:17:42Z (queue depth 4,621). Marker dedupe
matched PLAT-5104 description; appended as comment instead of opening
a duplicate incident ticket.

(Same alert id reuse pattern as v1.3 protocol §3 dedupe-on-burst.)
\`\`\`

### 10:18:45Z · maya@

\`\`\`
Confirmed unrelated to PLAT-5103. The webhook-worker code hasn't
changed in 11 days; the queue spike is on the consumer side.
Looking upstream.
\`\`\`

### 10:21Z · opchain-monitoring-ops · burst dedupe (3rd fire)

\`\`\`
<!-- opchain:oc-monitoring-ops:burst-event:PLAT-5104:event-3 -->

Third alert fire at 10:20:18Z. Marker matched — appended.
\`\`\`

### 10:24Z · maya@

\`\`\`
api.partner-x.com is returning 503s. Their status page is down too.
Their integration is the largest single consumer of our replay
queue (~30/s under normal conditions). Their 503s mean we can't
drain — items queue up.

Decision: wait for upstream recovery. Our retry-with-backoff is
working as designed; nothing for us to fix on our side. Will
auto-resolve when the queue drains.
\`\`\`

### 10:31:29Z · opchain-monitoring-ops · auto-resolved

\`\`\`
<!-- opchain:oc-monitoring-ops:auto-resolved:PLAT-5104 -->

Auto-resolved — duration 19m 28s.
Queue drained back to ~50; oldest item ~3s.
Transitioned: Resolved (PM pending).

Root cause (preliminary): an unrelated webhook receiver at
api.partner-x.com had a 19-min outage; their 503s caused our
replay queue to fill. Their status page confirms.
Postmortem required (sub-issue auto-created: PLAT-5104/postmortem).
\`\`\`

### 11:18Z · oc-monitoring-ops · postmortem published

\`\`\`
<!-- opchain:oc-monitoring-ops:postmortem:PLAT-5104 -->

Postmortem: https://onramp.dev/postmortems/2026-05-08-webhook-replay-queue
Remediation sub-tickets opened (2):
  - PLAT-5105 (vee@onramp.dev): add upstream-per-receiver timeout knob
  - PLAT-5106 (maya@onramp.dev): tune replay-queue-depth alert threshold
    to reduce noise on upstream-only outages

Transitioned: Done.
\`\`\`

## Timeline (UTC)

\`\`\`
10:11:30  api.partner-x.com begins returning 503s (their outage start)
10:11:38  webhook-replay queue depth begins climbing
10:12:01  alert webhook-replay-queue-depth fires
10:12:02  oc-monitoring-ops creates PLAT-5104; parent=PLAT-5103
10:12:02  oc-monitoring-ops pages maya
10:13:14  maya ack via PagerDuty (auto-mirrored)
10:13:30  maya rules out PLAT-5103 as causal
10:17:42  second alert fire (queue depth 4,621); marker dedupe → comment
10:18:00  maya looks at upstream metrics
10:18:45  maya confirms unrelated to PLAT-5103
10:20:18  third alert fire (queue depth 4,830); marker dedupe → comment
10:24:00  maya identifies upstream partner-x outage
10:24:30  decision: wait for upstream; our retries are doing the right thing
10:30:48  api.partner-x.com recovers
10:31:00  queue drain rate returns to ~35/s
10:31:29  oc-monitoring-ops auto-resolves
10:31:30  state: Resolved (PM pending)
11:18:00  maya publishes postmortem
11:18:14  oc-monitoring-ops opens PLAT-5105, PLAT-5106
11:18:15  state: Done
\`\`\`

## MTTR breakdown

| Phase | Window | Duration |
|---|---|---:|
| Detect | 10:11:38 → 10:12:01 (alert fires) | 23s |
| Acknowledge | 10:12:01 → 10:13:14 (PagerDuty ack) | 1m 13s |
| Diagnose | 10:13:14 → 10:24:00 (root cause identified) | 10m 46s |
| Mitigate | 10:24:00 → 10:30:48 (upstream recovery, not our action) | 6m 48s |
| Recover | 10:30:48 → 10:31:29 (queue drain) | 41s |
| **Total time-to-resolution** | 10:11:38 → 10:31:29 | **19m 51s** |

## Customer impact

**Zero.** The replay queue is by design tolerant of upstream delays;
all items eventually delivered. No customer-facing functionality
relies on the queue draining in real-time. Documented for postmortem
completeness; **status page not posted** (SEV-3 with zero customer
impact does not page comms team per existing policy).

## Post-mortem outline (published 11:18Z)

The full document at https://onramp.dev/postmortems/2026-05-08-webhook-replay-queue
has 5 sections:

1. **Summary** — partner-x outage; our replay queue absorbed it; no customer impact.
2. **Timeline** — copy of the section above.
3. **What worked** — alert fired in 23s; correlation to most-recent-deploy
   surfaced a candidate parent which we then correctly ruled out;
   retry-with-backoff drained naturally.
4. **What didn't work** — alert threshold is too aggressive (4,127 items
   is not "we have a problem", it's "an upstream is having a problem we
   can absorb"). Tuning tracked in PLAT-5106.
5. **Action items** — PLAT-5105, PLAT-5106.

## Sub-tickets (auto-created remediation)

| Ticket | Title | Owner | Due | Priority |
|---|---|---|---|---|
| [PLAT-5105](https://linear.app/onramp/issue/PLAT-5105) | Add upstream-per-receiver timeout knob | vee@ | 2026-05-15 | Medium |
| [PLAT-5106](https://linear.app/onramp/issue/PLAT-5106) | Tune replay-queue-depth alert (raise threshold; add upstream-aware suppression) | maya@ | 2026-05-12 | Medium |

## Lessons

- **What we'd do differently:** the alert's threshold is tuned for "our queue
  is broken", not "an upstream is broken." Raising the threshold +
  adding upstream-aware suppression (don't fire if the relevant upstream
  is also returning 5xx) would have de-noised this morning. PLAT-5106
  closes this.
- **What surprised us:** the marker-based dedupe worked exactly as the
  v1.3 protocol §3 describes — 3 alert fires in 8 minutes turned into
  1 ticket + 2 inline comments, not 3 duplicate tickets. The on-call
  experience was substantially calmer than the equivalent v1.2 prose
  flow would have been.
- **What worked well:** correlation to most-recent-deploy surfaced
  PLAT-5103 as a candidate; rapid review ruled it out; we didn't waste
  cycles re-investigating the deploy code path because the dashboards
  immediately pointed upstream.

## Linked

- parent (correlation, ultimately unrelated): [PLAT-5103 — Deploy: prod c4f8a21..ea71b9c](https://linear.app/onramp/issue/PLAT-5103)
- upstream-cause: api.partner-x.com outage 10:11:30 - 10:30:48 (per their status page)
- postmortem: https://onramp.dev/postmortems/2026-05-08-webhook-replay-queue
- remediation: PLAT-5105, PLAT-5106

Checkpoint: \`.checkpoints/oc-monitoring-ops.checkpoint.json\` → \`incidents.PLAT-5104\`.
`,
    },
    {
      id: "checkpoint-trace",
      label: "Cross-skill checkpoint trace (the deferred-action flush proof)",
      kind: "json.diff",
      body:
`# Checkpoint trace — what crossed the skill boundaries

**Schema reference:** \`.checkpoints/README.md\` § \`pm_deferred_actions[]\` ·
**Protocol reference:** \`skills/oc-integrations-engineer/references/pm-mcp-protocol.md\` §4

The v1.3 deferred-action queue (\`pm_deferred_actions[]\`) is the
load-bearing primitive. Below is the actual queue evolution captured
during this run, with timestamps. Each entry has a \`retriable\` flag
that controls whether \`/oc-deploy --retry-pm\` will replay it.

## 1. 10:38:14Z — oc-deploy-ops queues a deferred action

\`oc-deploy-ops.checkpoint.json\` (relevant excerpt):

\`\`\`json
{
  "schema_version": "1.3.0",
  "skill": "oc-deploy-ops",
  "phase": "post-prod-comment",
  "pm_deferred_actions": [
    {
      "id": "deferred-2026-05-08T10:38:14Z-7c2f",
      "skill": "oc-deploy-ops",
      "verb": "/oc-deploy",
      "operation": "add_comment",
      "provider": "linear",
      "tool_name": "mcp__claude_ai_Linear__save_comment",
      "ticket_id": "PLAT-5103",
      "marker": "<!-- opchain:oc-deploy-ops:prod-shipped:PLAT-5103 -->",
      "payload": {
        "issue_id": "PLAT-5103",
        "body": "<!-- opchain:oc-deploy-ops:prod-shipped:PLAT-5103 -->\\n\\nPROD SHIP · ea71b9c · v6.18.5..."
      },
      "queued_at": "2026-05-08T10:38:14Z",
      "last_attempt_at": "2026-05-08T10:38:29Z",
      "attempts": 3,
      "last_error": "Linear API returned 503 (3/3 attempts exhausted within 15s budget)",
      "retriable": true,
      "user_visible_message": "Linear is currently unreachable; the prod-shipped comment was deferred. The deploy itself is fine — ea71b9c is live. Run /oc-deploy --retry-pm to flush, or wait for the next pipeline pass."
    }
  ]
}
\`\`\`

The deploy itself **did not block**. Worker traffic shifted to
ea71b9c; \`/api/health\` returned the new SHA; smoke tests passed.
Only the Linear comment was deferred. The user sees a one-line
surface message (the \`user_visible_message\` field).

## 2. 10:42:03Z — \`/oc-deploy --retry-pm\` flushes

\`\`\`json
{
  "schema_version": "1.3.0",
  "skill": "oc-deploy-ops",
  "phase": "shipped",
  "pm_deferred_actions": [],
  "pm_flush_log": [
    {
      "id": "deferred-2026-05-08T10:38:14Z-7c2f",
      "flushed_at": "2026-05-08T10:42:03Z",
      "flush_attempt": 1,
      "result": "ok",
      "result_id": "comment-c8b1a3f4-...",
      "marker_pre_check": "absent",
      "duration_ms": 184
    }
  ]
}
\`\`\`

The marker \`<!-- opchain:oc-deploy-ops:prod-shipped:PLAT-5103 -->\` was
checked against \`list_comments(PLAT-5103)\` first — no match → safe
to write. If the user had run \`--retry-pm\` twice, the second pass
would short-circuit at the marker check and remove the queue entry
without re-posting.

## 3. Replay procedure

\`\`\`bash
# Inspect what's queued (read-only):
opchain checkpoint show oc-deploy-ops --field pm_deferred_actions

# Attempt to flush (will short-circuit on already-posted markers):
/oc-deploy --retry-pm

# Flush a specific deferred action by id (if you need to debug one):
/oc-deploy --retry-pm --id deferred-2026-05-08T10:38:14Z-7c2f

# What happens if the queue auto-flushes via the next /oc-deploy invocation?
# Same marker check; same idempotent outcome. The queue is bounded
# (max 32 entries per skill) to prevent unbounded growth.
\`\`\`

## 4. Contrasting example — a retriable: false event

Not all PM-MCP failures are retriable. Here's what a scope-violation
rejection looks like (synthetic example; not from this run):

\`\`\`json
{
  "pm_deferred_actions": [],
  "pm_user_facing_errors": [
    {
      "id": "error-2026-05-08T10:55:12Z-3a8e",
      "skill": "oc-deploy-ops",
      "verb": "/oc-deploy",
      "operation": "save_issue",
      "provider": "linear",
      "tool_name": "mcp__claude_ai_Linear__save_issue",
      "ticket_id": "PLAT-5103",
      "marker": null,
      "queued_at": "2026-05-08T10:55:12Z",
      "attempts": 1,
      "last_error": "Linear API returned 401: cross-team write not authorised (oc-deploy-ops attempted to transition PLAT-5103 owned by team OPS, agent is scoped to team PLAT)",
      "retriable": false,
      "user_visible_message": "Deploy ticket transition refused by Linear: cross-team write not authorised. This is a policy issue, not a transient failure — escalate to platform-eng for scope review."
    }
  ]
}
\`\`\`

**What differs from the deferred case:**

- \`retriable: false\` — does NOT go into \`pm_deferred_actions[]\`;
  goes into \`pm_user_facing_errors[]\` instead.
- 401/403/scope-related errors surface to the user immediately;
  retrying would not help.
- The user sees the error in the agent's response output, not as a
  silent queue.
- The error stays in the checkpoint until explicitly acknowledged
  (or the next pipeline phase clears it).

## 5. Cross-skill reads observed during the run

| Reading skill | Reads from | Why |
|---|---|---|
| oc-monitoring-ops | oc-deploy-ops.checkpoint.json | Find recent deploys for the incident-ticket "Recent deploys" field + likely-culprit parent link |
| oc-deploy-ops | oc-code-auditor.checkpoint.json | Read audit grade for the audit-gate decision (cached per-SHA) |
| oc-git-ops | oc-bug-check.checkpoint.json | Read pre-commit gate result |
| oc-release-ops | (every skill).checkpoint.json | Aggregate "what shipped since last release" for /oc-release plan |

All cross-reads use the public checkpoint schema in
\`oc-checkpoint-protocol\`'s SKILL.md — no skill imports another skill's
internal state.

## 6. What the v1.3 deferred-queue buys you

- **Crash safety.** Mid-flow agent restart (terminal closes, laptop
  sleeps, claude-code crashes) leaves the queue intact on disk; next
  invocation picks it up.
- **Transient-failure tolerance.** Linear's 503 doesn't fail the deploy.
- **Idempotency.** Re-running \`--retry-pm\` is always safe; the marker
  pre-check makes every operation a no-op if it's already done.
- **Bounded growth.** Max 32 entries per skill; overflow triggers a
  surfaced error (not silent loss).
- **Observable.** The queue + flush log are both in the checkpoint;
  a postmortem on a partial-failure deploy can reconstruct exactly
  what was deferred and when it flushed.

Checkpoint reference for this run: \`.checkpoints/oc-deploy-ops.checkpoint.json\`.
`,
    },
    {
      id: "audit-pipeline",
      label: "Audit-pipeline trace (HIPAA-style; out of scope but proves the contract)",
      kind: "audit.json",
      body:
`# Audit pipeline trace — what the broker would see (HIPAA / FedRAMP shape)

**Schema version:** \`mcp_audit_v1.3\` · **Sampling:** 100% (audit-grade, not analytics-grade) ·
**Retention:** illustrative; OnRamp is unregulated and does not run a brokered MCP environment

OnRamp is not regulated, so this trace is illustrative — it shows
what an audit-pipeline forwarder would record if PLAT-5102 had
ridden through a brokered MCP environment (e.g. the
mcp-enterprise-f500 scenario). The log is structured per-call with
the protocol §1 \`tool_overrides\` paths in place.

## Records

\`\`\`json
[
  {
    "ts": "2026-05-08T09:31:02.118Z",
    "actor": "claude-code-session",
    "actor_id": "session-bf21",
    "user": "maya@onramp.dev",
    "tool": "mcp__corp-linear-broker__get_issue",
    "args_hash": "sha256:c1f...",
    "args": { "id": "PLAT-5102" },
    "result": "ok",
    "marker": null,
    "skill": "oc-git-ops",
    "verb": "/oc-git-sync",
    "correlation_id": "session-bf21:1",
    "broker_pod": "linear-broker-7c9f-x4n2",
    "policy_version_at_call": "v1.4"
  },
  {
    "ts": "2026-05-08T09:31:14.882Z",
    "actor": "claude-code-session",
    "user": "maya@onramp.dev",
    "tool": "mcp__corp-linear-broker__list_comments",
    "args_hash": "sha256:a2b...",
    "result": "ok",
    "match_count": 0,
    "marker": "<!-- opchain:oc-git-ops:pr-opened:#412 -->",
    "skill": "oc-git-ops",
    "verb": "/oc-git-sync",
    "correlation_id": "session-bf21:2",
    "broker_pod": "linear-broker-7c9f-x4n2",
    "policy_version_at_call": "v1.4"
  },
  {
    "ts": "2026-05-08T10:38:14.114Z",
    "actor": "claude-code-session",
    "user": "oc-deploy-ops",
    "tool": "mcp__corp-linear-broker__save_comment",
    "args_hash": "sha256:f3e...",
    "result": "503",
    "retriable": true,
    "marker": "<!-- opchain:oc-deploy-ops:prod-shipped:PLAT-5103 -->",
    "skill": "oc-deploy-ops",
    "verb": "/oc-deploy",
    "deferred": true,
    "attempts": 3,
    "correlation_id": "session-bf21:14",
    "broker_pod": "linear-broker-7c9f-x4n2",
    "policy_version_at_call": "v1.4",
    "downstream_error": "linear.upstream.unavailable"
  },
  {
    "ts": "2026-05-08T10:42:03.029Z",
    "actor": "claude-code-session",
    "user": "oc-deploy-ops",
    "tool": "mcp__corp-linear-broker__save_comment",
    "args_hash": "sha256:f3e...",
    "result": "ok",
    "comment_id": "comment-c8b1a3f4-...",
    "marker": "<!-- opchain:oc-deploy-ops:prod-shipped:PLAT-5103 -->",
    "skill": "oc-deploy-ops",
    "verb": "/oc-deploy --retry-pm",
    "flushed_from": "deferred-2026-05-08T10:38:14Z-7c2f",
    "correlation_id": "session-bf21:14",
    "broker_pod": "linear-broker-7c9f-x4n2",
    "policy_version_at_call": "v1.4"
  }
]
\`\`\`

## Detection rules (Splunk SPL — illustrative)

A regulated environment would run these on the audit log to catch
patterns that warrant a human review.

### Rule 1 — Deferred action stuck in queue

\`\`\`
index=mcp_audit
  | search deferred=true
  | stats max(_time) as last_deferred by correlation_id, user, skill
  | join correlation_id [search index=mcp_audit flushed_from=*]
  | where flushed_from IS NULL AND last_deferred < relative_time(now(), "-1h")
  | table user, skill, correlation_id, last_deferred
\`\`\`

Fires: Slack #ops-mcp-alerts after 1 hour of unflushed queue.
Action: investigate; deferred actions older than 1h usually indicate
either a persistent upstream outage or a deferred-queue bug.

### Rule 2 — Retry storm on the same marker

\`\`\`
index=mcp_audit
  | search marker=*
  | stats count by marker, user, skill
  | where count > 5
\`\`\`

Fires: Slack #ops-mcp-alerts on > 5 retries against the same marker.
Action: investigate; this either means the marker check is failing
(bug) or the agent is in a retry loop (bug).

## Properties an auditor cares about

- **Every call has an actor, a user, and a correlation id.** The actor
  is the agent runtime; the user is the human owning the session;
  the correlation id ties together related calls (e.g. defer + flush).
- **The deferred-then-flushed call is a single logical event**
  (correlation_id reused) so an auditor sees the full timeline.
- **Markers are the idempotency check.** Matching the marker proves
  the flush was idempotent (or the retry was a no-op).
- **503 retries are visible without inflating the call count.** The
  3 attempts within the 15s budget are summarised in \`attempts\`
  rather than logged 3 times — keeps the audit pipeline cost
  bounded while preserving forensic detail.
- **\`broker_pod\` + \`policy_version_at_call\`** let an auditor replay
  a historical event against the policy in force at the time.
- **\`args_hash\`** allows "did agent X and agent Y see the same input?"
  forensic correlation without storing the args body in the SIEM.
  (For PHI / CUI environments, args body is held in a 7-day encrypted
  trace at the broker — see \`mcp-enterprise-f500\` audit-log artifact.)

## How this scales to brokered environments

OnRamp's run doesn't actually hit a broker; the same shape applies
when it does:

- \`tool_overrides\` in \`pm.yaml\` points calls at the broker MCP names.
- The broker emits these records to \`fluentbit → Splunk HEC\` (hot)
  + \`BigQuery\` (cold, 7-year retention).
- Detection rules run on the hot index.
- Forensic decrypt (body trace) needs Privacy Officer + IR Lead 2-of-2.

See the F500 scenario's \`audit-log\` artifact for the production-grade
pipeline this trace illustrates.

Checkpoint: \`.checkpoints/oc-monitoring-ops.checkpoint.json\` → \`audit_pipeline_traces\`.
`,
    },
    {
      id: "release-stamp",
      label: "Production /api/health response after the ship",
      kind: "json",
      body:
`{
  "ok": true,
  "service": "onramp-api",
  "version": "ea71b9c",
  "build_id": "v6.18.5",
  "ts": "2026-05-08T10:42:18.221Z",
  "deploy_ticket": "PLAT-5103",
  "linked_tickets": ["PLAT-5102"]
}
`,
    },
  ],
  skills: [
    "oc-app-architect",
    "oc-git-ops",
    "oc-code-auditor",
    "oc-bug-check",
    "oc-deploy-ops",
    "oc-monitoring-ops",
    "oc-integrations-engineer",
  ],
  runtime: "~12 minutes",
  steps: [
    {
      type: "beat",
      label: "09:14Z — alert paged Maya, she filed PLAT-5102",
      caption: "p99 climbed 120ms → 3.4s on /api/customers. The opchain pipeline takes the ticket from here.",
      skills: [],
    },
    {
      type: "exchange",
      role: "user",
      content:
        "PagerDuty paged me on api-latency-customers-p99. I filed PLAT-5102 with the alert payload. Take it and `/oc-git-sync PLAT-5102`.",
    },
    {
      type: "exchange",
      role: "claude",
      skill: "oc-git-ops",
      content:
`On it. Reading PLAT-5102 from Linear, then walking the oc-git-ops PM-MCP loop. The v1.3 protocol gives me concrete tool names + a marker check before any write.

**Step 1 — fetch the ticket.**
\`mcp__claude_ai_Linear__get_issue(id="PLAT-5102")\` → 142ms, retriable failure budget untouched.

Ticket type is **Bug**, fingers the index on \`(team_id, created_at)\`, links to the 2026-05-07 03:05Z migration cleanup as the suspect commit. That gives me what I need to bisect.

**Step 2 — bisect.** Reading the migration commit before writing any code.

\`\`\`
$ git log --oneline -- migrations/
a221f08  2026-05-07 03:05  data: drop dupe indexes (cleanup)
8f3c7d2  2026-05-04 14:10  feat: customer.csv streaming

$ git show a221f08 -- migrations/
diff --git a/migrations/20260507_drop_dupe_indexes.sql b/migrations/20260507_drop_dupe_indexes.sql
+++ b/migrations/20260507_drop_dupe_indexes.sql
+DROP INDEX IF EXISTS idx_customers_team_id_created_at;
+DROP INDEX IF EXISTS idx_events_team_id_created_at;
+-- ... 6 more
\`\`\`

**Confirmed.** The migration dropped \`idx_customers_team_id_created_at\`
thinking it was a duplicate of \`idx_customers_team_id\`. It's not — the
composite is the only one that supports the cursor's compound predicate
(\`team_id = $1 AND created_at > $2 ORDER BY created_at\`). We need it
back.

**Step 3 — write the fix + the regression test.**

\`\`\`sql
-- migrations/20260508_restore_paginate_index.sql
CREATE INDEX CONCURRENTLY IF NOT EXISTS
  idx_customers_team_id_created_at
  ON customers (team_id, created_at DESC);
\`\`\`

\`\`\`ts
// tests/regression/test_customer_list_plan.py
def test_planner_uses_composite_index_after_fix():
    """Asserts the planner picks Index Scan, not Seq Scan, for the
    customer-list cursor query. Catches the regression if the index
    gets dropped again."""
    explain = db.execute(
        "EXPLAIN (FORMAT JSON) "
        "SELECT id, name FROM customers "
        "WHERE team_id = %s AND created_at > %s "
        "ORDER BY created_at LIMIT 200",
        ("team_acme", "2025-01-01"),
    ).fetchone()[0]
    node = explain[0]["Plan"]
    assert _find_node_type(node, "Seq Scan on customers") is None, \
        "Planner reverted to Seq Scan; composite index likely missing"
    assert _find_node_type(node, "Index Scan") is not None, \
        "Expected Index Scan on idx_customers_team_id_created_at"
\`\`\`

**Step 4 — pre-commit gate (oc-bug-check)** runs and passes (12.4s).

**Step 5 — open the PR.** Pre-write check: \`mcp__claude_ai_Linear__list_comments(PLAT-5102)\` → no marker match → safe to write.

\`mcp__claude_ai_Linear__save_comment\`:

\`\`\`
<!-- opchain:oc-git-ops:pr-opened:#2243 -->
PR opened: https://github.com/onramp-inc/platform/pull/2243
Fix: restore composite index dropped by a221f08.
Regression test added.
\`\`\`

Then \`mcp__claude_ai_Linear__save_issue(id="PLAT-5102", state="In Review")\` — transitions PLAT-5102.

Branch + commit + PR + comment + state transition. Five tool calls, zero retries. Handing off to oc-code-auditor + oc-bug-check then to oc-deploy-ops for staging.`,
      artifacts: ["plat-5102", "pm-yaml"],
    },
    {
      type: "exchange",
      role: "claude",
      skill: "oc-code-auditor",
      content:
`oc-code-auditor /oc-audit pre-deploy on PR #2243.

\`\`\`
Files reviewed:        2 (migrations/20260508_restore_paginate_index.sql,
                          tests/regression/test_customer_list_plan.py)
Findings:              0 blocking, 1 advisory
Advisory #1:           consider adding a comment to services/customers.ts
                       documenting which index supports the cursor query
                       (so the next "duplicate index cleanup" doesn't repeat
                       this incident). Not blocking; logging as PLAT-5107.
Tests:                 1 new regression, 153 existing, 0 failing
Coverage:              new code 100%
Type-check:            PASS
Lint:                  PASS
Grade:                 A-
Wall-clock:            9.2s
\`\`\`

v1.3: posting back to Linear with a stable marker.

\`\`\`
mcp__claude_ai_Linear__save_comment("PLAT-5102",
  body="<!-- opchain:oc-code-auditor:audit-posted:#2243 -->
        Auditor: Grade A-. 0 blocking, 1 advisory.
        Advisory: document which index supports the cursor query
        (filed as PLAT-5107 for future cleanup).")
\`\`\`

Bug-check returned PASS (1.1s). PR is mergeable; oc-deploy-ops can take over.`
    },
    {
      type: "beat",
      label: "10:08Z — staging deploy",
      caption: "Audit gate green. oc-deploy-ops creates PLAT-5103 (deploy ticket) parent-linked to PLAT-5102.",
      skills: ["oc-deploy-ops"],
    },
    {
      type: "exchange",
      role: "user",
      content: "/oc-deploy staging",
    },
    {
      type: "exchange",
      role: "claude",
      skill: "oc-deploy-ops",
      content:
`**Audit gate** (oc-code-auditor + oc-security-auditor + oc-bug-check) → all PASS, cached per-SHA from /oc-git-sync.

**Pre-create check for the deploy ticket:**
\`mcp__claude_ai_Linear__list_issues(team="PLAT", query="opchain:oc-deploy-ops:deploy-created:prod:ea71b9c")\` → no match → safe to create.

\`mcp__claude_ai_Linear__save_issue\` (no \`id\` — creates):

\`\`\`
title: "Deploy: prod c4f8a21..ea71b9c"
description: <!-- opchain:oc-deploy-ops:deploy-created:prod:ea71b9c --> ...
issue_type: Deploy
parent: PLAT-5102
labels: [opchain, agent-driven, deploy, hotfix]
\`\`\`

→ PLAT-5103 created.

**Wrangler deploy --env staging** → 34s. Migration applied (concurrent index build 41s on staging's customer table — production will take ~67s based on row-count ratio). Smoke tests:

- \`/api/customers?cursor=...&limit=200\` p99 = **78ms** ✓ (was 3.4s on prod baseline)
- \`/api/health\` 200, SHA ea71b9c ✓
- \`/api/customers.csv?limit=200\` 200, BOM intact ✓
- \`k6 run --vus 50 --duration 60s\` — p95 142ms, p99 198ms ✓ (5× current load held under threshold)

**Pre-write check** for the staging-verified comment: \`list_comments(PLAT-5103)\` → no match → write it. \`save_issue(id="PLAT-5103", state="Staging verified")\`.

Ready to ship to prod.`,
      artifacts: ["deploy-ticket"],
    },
    {
      type: "exchange",
      role: "user",
      content: "/oc-deploy prod",
    },
    {
      type: "exchange",
      role: "claude",
      skill: "oc-deploy-ops",
      content:
`**Wrangler deploy** (no --env) → 8.9s build + traffic shift; concurrent index build on prod took 67s in the background, non-blocking. Traffic shifted at 10:38:08Z. \`/api/health\` confirms ea71b9c.

**Real-time validation:**
- p99 latency dropped from 3.4s to ~110ms within 15s of traffic shift
- acme-inc tenant slice dropped from 4.9s p99 to 130ms
- query plan flipped to Index Scan immediately on first request post-index-build

**Comment on PLAT-5103 (prod-shipped):**
\`mcp__claude_ai_Linear__save_comment\` → **503 from Linear**. Retry policy kicks in (per protocol §4):
- Attempt 2 (1.0s wait + jitter) → 503
- Attempt 3 (3.0s wait + jitter) → 503
- Budget exhausted at 15.1s.

Per protocol §4, deferring instead of failing. Writing to \`oc-deploy-ops.checkpoint.json\`:

\`\`\`json
"pm_deferred_actions": [{
  "id": "deferred-2026-05-08T10:38:14Z-7c2f",
  "skill": "oc-deploy-ops",
  "verb": "/oc-deploy",
  "operation": "add_comment",
  "marker": "<!-- opchain:oc-deploy-ops:prod-shipped:PLAT-5103 -->",
  "retriable": true,
  "last_error": "Linear API returned 503 (3/3 attempts within 15s budget)",
  ...
}]
\`\`\`

**The deploy itself is fine.** ea71b9c is live; PLAT-5102 is fixed; latency restored. The only thing missing is the audit comment on Linear, which I'll flush later.

Surfacing: \`/oc-deploy --retry-pm\` to flush 1 deferred action.`,
      artifacts: ["release-stamp"],
    },
    {
      type: "exchange",
      role: "user",
      content: "Try the flush.",
    },
    {
      type: "exchange",
      role: "claude",
      skill: "oc-deploy-ops",
      content:
`\`/oc-deploy --retry-pm\`:

Reading \`oc-deploy-ops.checkpoint.json\` → 1 entry, \`retriable: true\`.

**Pre-write check:** \`mcp__claude_ai_Linear__list_comments(PLAT-5103)\` → marker \`<!-- opchain:oc-deploy-ops:prod-shipped:PLAT-5103 -->\` not present → safe to write.

\`mcp__claude_ai_Linear__save_comment\` → **OK** (Linear recovered ~3 minutes ago).

Removing the deferred entry, appending to \`pm_flush_log[]\`:

\`\`\`
flushed 1 / failed 0 / skipped 0
\`\`\`

If you'd run this twice by mistake, the second pass would match the marker and remove the entry without re-posting. Same shape would apply if a session crashed mid-flush.

PLAT-5103 is now \`Shipped\`. Each linked ticket (PLAT-5102) gets its own \`linked-shipped\` comment with marker \`<!-- opchain:oc-deploy-ops:linked-shipped:PLAT-5103:PLAT-5102 -->\`. PLAT-5102 transitions to \`Done\`.`,
      artifacts: ["checkpoint-trace"],
    },
    {
      type: "exchange",
      role: "user",
      content: "What if the deferred queue had grown to N entries — say if Linear was out for an hour and we ran a half-dozen deploys?",
    },
    {
      type: "exchange",
      role: "claude",
      skill: "oc-deploy-ops",
      content:
`Bounded growth is by design. Three policies kick in:

1. **Per-skill cap.** Each skill's \`pm_deferred_actions[]\` is capped at **32 entries.** Overflow doesn't silently drop — it triggers a \`retriable: false\` user-facing error so you know the queue is filling. The cap prevents an unattended session from accumulating thousands of deferred writes if an upstream is out for days.

2. **Per-marker deduplication.** Two deferred actions with the same marker collapse to one entry on insertion. So if you ran \`/oc-deploy\` six times during a Linear outage and each tried to post the same \`prod-shipped\` comment on the same ticket, you'd still have one queue entry, not six. (Different deploys produce different markers because they include the deploy id.)

3. **TTL on deferred entries.** Entries older than **7 days** are pruned with a surfaced warning ("3 deferred comments older than 7d were dropped — they're audit-log only, not retryable"). The pipeline assumes that if you haven't flushed in a week, the comment is no longer load-bearing.

The flush behaviour scales linearly: \`--retry-pm\` walks the queue, runs the marker pre-check on each entry, attempts each that isn't already posted. If Linear is still flaky during the flush, those re-defer with their \`attempts\` counter incremented; once attempts hit 6 the entry escalates to \`retriable: false\` and surfaces as a user-facing error.

In the F500 / regulated environments (where the broker is between us and Linear), the broker has its own retry / dead-letter-queue policy underneath, so the agent's queue stays small even during long outages. See \`audit-pipeline\` artifact for the broker shape.`,
    },
    {
      type: "beat",
      label: "10:12Z — unrelated incident fires",
      caption: "oc-monitoring-ops opens PLAT-5104 against PLAT-5103 (parent link), demonstrates marker-based dedupe on the burst.",
      skills: ["oc-monitoring-ops"],
    },
    {
      type: "exchange",
      role: "claude",
      skill: "oc-monitoring-ops",
      content:
`Alert \`webhook-replay-queue-depth\` at 10:12:01Z — separate service from the one I just fixed.

**Pre-create check:** \`list_issues(team="PLAT", query="opchain:oc-monitoring-ops:incident-fired:evt-2026-05-08-101201")\` → no match → safe to create.

\`save_issue\` opens PLAT-5104. Parent set to **PLAT-5103** (most recent open deploy ticket — likely-culprit link, even though I'll quickly note in the body that the deploy doesn't touch this service).

Second alert fires at 10:17:42Z (queue depth 4,621). Pre-create check would normally collide on the alert-event-id, but burst events use a per-event marker — \`<!-- opchain:oc-monitoring-ops:burst-event:PLAT-5104:event-2 -->\` — so I append a comment instead of opening a duplicate ticket. Three more alert fires in the next four minutes; same dedupe — three comments, one ticket.

Auto-resolves at 10:31:29Z (queue drained; upstream partner-x recovered). Postmortem published 11:18Z; remediation sub-tickets PLAT-5105 + PLAT-5106 opened with markers \`<!-- opchain:oc-monitoring-ops:remediation:PLAT-5104:item-1 -->\` and \`...:item-2 -->\`. PLAT-5104 transitions to \`Done\`.`,
      artifacts: ["incident-ticket"],
    },
    {
      type: "beat",
      label: "11:20Z — release recap",
      caption: "Six skills wrote on this thread. Every comment carries a marker; every retry resolved cleanly.",
    },
    {
      type: "exchange",
      role: "user",
      content: "Summarise — what made the v1.3 loop work where v1.2's prose didn't?",
    },
    {
      type: "exchange",
      role: "claude",
      skill: "oc-integrations-engineer",
      content:
`Three things landed in v1.3 that turned the v1.2 prose into a runtime.

**1. Concrete tool-name registry.** v1.2 said "call \`mcp.<provider>.get_issue\`". A Claude session reading that prose had to guess the actual tool name — \`mcp__claude_ai_Linear__get_issue\` vs \`linear.getIssue\` vs whatever. v1.3's \`pm-mcp-protocol.md §1\` is a flat table that a session can match against the tools its MCP server actually exposes. \`tool_overrides\` in \`pm.yaml\` handles the brokered / regulated case (corp-prefixed tools).

**2. Idempotency markers, not just retries.** Every comment composed by every skill carries a \`<!-- opchain:<skill>:<event>:<id> -->\` marker. The pre-write check fetches comments and matches the marker before posting. So when:
  - the session crashed mid-deploy and was resumed, the marker matched → no duplicate post;
  - Linear returned 503 mid-flush and we retried twice, the second pass matched → no duplicate post;
  - the user typed \`--retry-pm\` twice by accident, the second pass matched → no-op.

This is what makes the loop **safe to retry**, not just retriable.

**3. Deferred-action queue with explicit \`retriable\` flag.** The 503 mid-deploy didn't crash the deploy. The intended write was queued in \`oc-deploy-ops.checkpoint.json\` with \`retriable: true\` — \`/oc-deploy --retry-pm\` flushes it later. 4xx-non-429 errors get \`retriable: false\` so a scope-violation broker rejection surfaces to the user instead of retrying forever. The queue is bounded at 32 entries per skill with 7d TTL.

The audit pipeline trace (artifact below) shows what a brokered environment would log for this run — same ops, same markers, plus broker-side correlation ids tying agent calls to the audit record.`,
      artifacts: ["audit-pipeline"],
    },
  ],
};
