#!/usr/bin/env bash
# Sprint 6 — build the Astro site + materialize it in public/ so the
# Worker's ASSETS binding serves it. Preserves public/docs (still synced
# from skills/), public/opchain-skills.zip, public/favicon.svg.
#
# Runs as part of `npm run prebuild`; also callable directly.

set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SITE="${ROOT}/site"
DIST="${SITE}/dist"
PUBLIC="${ROOT}/public"

# Preserved entries (synced/generated by other build steps).
# Favicon is NOT preserved here — it's sourced from site/public/favicon.svg
# and copied to dist/favicon.svg by Astro.
PRESERVE=(docs opchain-skills.zip)

echo "[build-site] astro build"
(cd "${SITE}" && npm run build)

if [ ! -d "${DIST}" ]; then
  echo "::error::astro build finished but ${DIST} is missing"
  exit 1
fi

echo "[build-site] cleaning public/ (preserving: ${PRESERVE[*]})"
# Snapshot preserved dirs/files into a temp dir, wipe public/, restore.
TMP="$(mktemp -d)"
for entry in "${PRESERVE[@]}"; do
  if [ -e "${PUBLIC}/${entry}" ]; then
    mv "${PUBLIC}/${entry}" "${TMP}/"
  fi
done

rm -rf "${PUBLIC}"
mkdir -p "${PUBLIC}"

cp -R "${DIST}/." "${PUBLIC}/"

for entry in "${PRESERVE[@]}"; do
  if [ -e "${TMP}/${entry}" ]; then
    mv "${TMP}/${entry}" "${PUBLIC}/${entry}"
  fi
done
rmdir "${TMP}" 2>/dev/null || true

echo "[build-site] injecting CSP nonce placeholder"
node "${ROOT}/scripts/inject-nonce-placeholder.mjs"

echo "[build-site] public/ rebuilt"
