#!/usr/bin/env bash
# Sprint 6 — build the Astro site + materialize it in public/ so the
# Worker's ASSETS binding serves it. Preserves public/docs (synced from
# skills/), public/opchain-skills.zip, and the per-skill
# public/skills/<id>.zip bundles — all produced by earlier build steps
# (sync-docs, make-zip) and absent from Astro's dist output.
#
# Runs as part of `npm run prebuild`; also callable directly.

set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SITE="${ROOT}/site"
DIST="${SITE}/dist"
PUBLIC="${ROOT}/public"

# Preserved entries (synced/generated by other build steps).
# Favicon is NOT preserved here — it's sourced from site/public/favicon.svg
# and copied to dist/favicon.svg by Astro.
PRESERVE=(docs opchain-skills.zip)

echo "[build-site] astro build"
(cd "${SITE}" && npm run build)

if [ ! -d "${DIST}" ]; then
  echo "::error::astro build finished but ${DIST} is missing"
  exit 1
fi

echo "[build-site] cleaning public/ (preserving: ${PRESERVE[*]})"
# Snapshot preserved dirs/files into a temp dir, wipe public/, restore.
TMP="$(mktemp -d)"
for entry in "${PRESERVE[@]}"; do
  if [ -e "${PUBLIC}/${entry}" ]; then
    mv "${PUBLIC}/${entry}" "${TMP}/"
  fi
done

# The per-skill bundles (skills/<id>.zip) sit in the same directory Astro
# generates its skills/<id>/ pages into, so they can't be preserved as a
# whole top-level entry without clobbering that output. Snapshot just the
# loose .zip files and merge them back into the rebuilt skills/ dir below.
mkdir -p "${TMP}/skills"
for z in "${PUBLIC}"/skills/*.zip; do
  if [ -e "${z}" ]; then
    mv "${z}" "${TMP}/skills/"
  fi
done

rm -rf "${PUBLIC}"
mkdir -p "${PUBLIC}"

cp -R "${DIST}/." "${PUBLIC}/"

for entry in "${PRESERVE[@]}"; do
  if [ -e "${TMP}/${entry}" ]; then
    mv "${TMP}/${entry}" "${PUBLIC}/${entry}"
  fi
done

# Restore the per-skill bundles alongside the freshly built skills/ pages.
for z in "${TMP}"/skills/*.zip; do
  if [ -e "${z}" ]; then
    mkdir -p "${PUBLIC}/skills"
    mv "${z}" "${PUBLIC}/skills/"
  fi
done
rmdir "${TMP}/skills" 2>/dev/null || true
rmdir "${TMP}" 2>/dev/null || true

echo "[build-site] injecting CSP nonce placeholder"
node "${ROOT}/scripts/inject-nonce-placeholder.mjs"

echo "[build-site] public/ rebuilt"
