#!/usr/bin/env node
/**
 * Codegen: read src/lib/flags/registry.js → emit site/src/lib/flags/registry.ts.
 *
 * The site needs the union of flag names + the defaults, but we don't want
 * Astro to import worker-shaped JS. So we emit a typed TS mirror: same
 * defaults, same name list, but no `eval.js` / `posthog.js` deps.
 *
 * Output is gitignored after the first run (still committed for review on
 * the first PR; future PRs will produce the same file deterministically).
 */

import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { mkdirSync, writeFileSync } from "node:fs";

import { FLAGS, FLAG_NAMES, PUBLIC_FLAG_NAMES, CATEGORIES } from "../src/lib/flags/registry.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = join(ROOT, "site", "src", "lib", "flags");
const OUT = join(OUT_DIR, "registry.ts");

function jsonValue(v) {
  return JSON.stringify(v);
}

function emit() {
  const lines = [];
  lines.push("// AUTO-GENERATED by scripts/gen-flags.mjs — do not edit by hand.");
  lines.push("// Regenerate with `npm run gen-flags`.");
  lines.push("");
  lines.push("export type FlagName =");
  FLAG_NAMES.forEach((n, i) => {
    lines.push(`  | ${jsonValue(n)}${i === FLAG_NAMES.length - 1 ? ";" : ""}`);
  });
  lines.push("");
  lines.push(`export type FlagCategory = ${CATEGORIES.map(jsonValue).join(" | ")};`);
  lines.push("");
  lines.push("export type FlagValue = boolean | string | number;");
  lines.push("");
  lines.push("export interface FlagDef {");
  lines.push("  name: FlagName;");
  lines.push("  type: \"boolean\" | \"string\" | \"number\";");
  lines.push("  default: FlagValue;");
  lines.push("  category: FlagCategory;");
  lines.push("  owner: string;");
  lines.push("  description: string;");
  lines.push("}");
  lines.push("");
  lines.push("export const FLAGS: Readonly<Record<FlagName, FlagDef>> = Object.freeze({");
  for (const name of FLAG_NAMES) {
    const def = FLAGS[name];
    lines.push(`  ${jsonValue(name)}: Object.freeze({`);
    lines.push(`    name: ${jsonValue(def.name)},`);
    lines.push(`    type: ${jsonValue(def.type)},`);
    lines.push(`    default: ${jsonValue(def.default)},`);
    lines.push(`    category: ${jsonValue(def.category)},`);
    lines.push(`    owner: ${jsonValue(def.owner)},`);
    lines.push(`    description: ${jsonValue(def.description)},`);
    lines.push(`  }),`);
  }
  lines.push("}) as Readonly<Record<FlagName, FlagDef>>;");
  lines.push("");
  lines.push("export const FLAG_NAMES: ReadonlyArray<FlagName> = Object.freeze([");
  for (const n of FLAG_NAMES) lines.push(`  ${jsonValue(n)},`);
  lines.push("]) as ReadonlyArray<FlagName>;");
  lines.push("");
  lines.push("export const PUBLIC_FLAG_NAMES: ReadonlyArray<FlagName> = Object.freeze([");
  for (const n of PUBLIC_FLAG_NAMES) lines.push(`  ${jsonValue(n)},`);
  lines.push("]) as ReadonlyArray<FlagName>;");
  lines.push("");
  lines.push("export function getDefault(name: FlagName): FlagValue {");
  lines.push("  return FLAGS[name].default;");
  lines.push("}");
  lines.push("");
  lines.push("export function isKnown(name: string): name is FlagName {");
  lines.push("  return Object.prototype.hasOwnProperty.call(FLAGS, name);");
  lines.push("}");
  lines.push("");

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT, lines.join("\n"), "utf8");
  console.log(`✓ flag registry mirror generated: ${FLAG_NAMES.length} flags → ${OUT.replace(ROOT + "/", "")}`);
}

emit();
